"""Local infrastructure adapters for the AuthProvider port."""

from foundry_lite.application.ports.auth_provider import AuthProvider
from foundry_lite.infrastructure.auth.local import (
    HEADER_ROLES_KEY,
    HEADER_TENANT_KEY,
    HEADER_USER_ATTRIBUTES_KEY,
    HEADER_USER_KEY,
    DemoAuthProvider,
    HeaderTrustAuthProvider,
)
from foundry_lite.infrastructure.auth.oauth_token_issuer import (
    OAUTH_AUDIENCE_ENV,
    OAUTH_ISSUER_ENV,
    OAUTH_PRIVATE_KEY_PATH_ENV,
    LocalOAuthTokenIssuer,
)
from foundry_lite.infrastructure.auth.oidc import (
    AUTHORIZATION_HEADER,
    OIDC_ALLOWED_CLIENT_IDS_JSON_ENV,
    OIDC_AUDIENCE_ENV,
    OIDC_CLIENT_ID_CLAIM_ENV,
    OIDC_DISCOVERY_JSON_ENV,
    OIDC_DISCOVERY_URL_ENV,
    OIDC_GRANT_TYPE_CLAIM_ENV,
    OIDC_GRANT_TYPE_VALUE_ENV,
    OIDC_HUMAN_GRANT_CLAIM_ENV,
    OIDC_HUMAN_GRANT_VALUE_ENV,
    OIDC_ISSUER_ENV,
    OIDC_JWKS_JSON_ENV,
    OIDC_OSDK_APP_CLAIM_ENV,
    OIDC_REVOKED_JTIS_JSON_ENV,
    OIDC_ROLES_CLAIM_ENV,
    OIDC_SCOPE_CLAIM_ENV,
    OIDC_SERVICE_ACCOUNT_CLAIM_ENV,
    OIDC_SESSION_CLAIM_ENV,
    OIDC_TENANT_CLAIM_ENV,
    OIDC_USER_ATTRIBUTES_CLAIM_ENV,
    JwtOidcAuthConfig,
    JwtOidcAuthProvider,
)
from foundry_lite.infrastructure.auth.profiles import (
    AUTH_PROFILE_ENV,
    DEFAULT_AUTH_PROFILE,
    DEFAULT_RUNTIME_PROFILE,
    RUNTIME_PROFILE_ENV,
    AuthProfileConfigurationError,
    auth_provider_for_profile,
    auth_provider_from_env,
)

__all__ = [
    "AUTH_PROFILE_ENV",
    "AUTHORIZATION_HEADER",
    "DEFAULT_AUTH_PROFILE",
    "DEFAULT_RUNTIME_PROFILE",
    "HEADER_ROLES_KEY",
    "HEADER_TENANT_KEY",
    "HEADER_USER_KEY",
    "HEADER_USER_ATTRIBUTES_KEY",
    "RUNTIME_PROFILE_ENV",
    "AuthProfileConfigurationError",
    "AuthProvider",
    "DemoAuthProvider",
    "HeaderTrustAuthProvider",
    "JwtOidcAuthConfig",
    "JwtOidcAuthProvider",
    "LocalOAuthTokenIssuer",
    "OAUTH_AUDIENCE_ENV",
    "OAUTH_ISSUER_ENV",
    "OAUTH_PRIVATE_KEY_PATH_ENV",
    "OIDC_ALLOWED_CLIENT_IDS_JSON_ENV",
    "OIDC_AUDIENCE_ENV",
    "OIDC_CLIENT_ID_CLAIM_ENV",
    "OIDC_DISCOVERY_JSON_ENV",
    "OIDC_DISCOVERY_URL_ENV",
    "OIDC_GRANT_TYPE_CLAIM_ENV",
    "OIDC_GRANT_TYPE_VALUE_ENV",
    "OIDC_HUMAN_GRANT_CLAIM_ENV",
    "OIDC_HUMAN_GRANT_VALUE_ENV",
    "OIDC_ISSUER_ENV",
    "OIDC_JWKS_JSON_ENV",
    "OIDC_REVOKED_JTIS_JSON_ENV",
    "OIDC_ROLES_CLAIM_ENV",
    "OIDC_SESSION_CLAIM_ENV",
    "OIDC_OSDK_APP_CLAIM_ENV",
    "OIDC_SCOPE_CLAIM_ENV",
    "OIDC_SERVICE_ACCOUNT_CLAIM_ENV",
    "OIDC_TENANT_CLAIM_ENV",
    "OIDC_USER_ATTRIBUTES_CLAIM_ENV",
    "auth_provider_for_profile",
    "auth_provider_from_env",
]
