// generated by scripts/generate_sdk_ts.py; do not edit by hand
export const ONTOLOGY_CONTRACT_FINGERPRINT = "a622ceca207f76d4";
export const SDK_CLIENT_SURFACE = {"actions":{"ApproveOrder":["apply"]},"helpers":["createFoundryLiteClient","createRequestId","expectedObjectVersion","idempotencyKey","isRetryableFoundryLiteError","normalizeFoundryLiteError","requestContextHeaders"],"objects":{"Customer":["get","query"],"Order":["get","query"]},"operations":{"backupRestore":["preflight","startRestoreMode","restoreModeStatus","approveResume"],"deadLetterRecords":["list","get","retry","bulkRetry","discard"],"icebergMaintenance":["plan"],"observability":["detect"],"reconciliation":["resolve"],"workflows":["startConnectorSync","get"]}};

export function idempotencyKey(actionName, objectId) {
  return `${actionName}-${objectId}-${Date.now()}`;
}

export function createRequestId(scope = "sdk") {
  return `${scope}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

export class FoundryLiteApiError extends Error {
  constructor(status, code, message, details, requestId, retryable) {
    super(message);
    this.name = "FoundryLiteApiError";
    this.status = status;
    this.code = code;
    this.details = details;
    this.requestId = requestId;
    this.retryable = retryable;
  }
}

export function requestContextHeaders(context = {}) {
  const headers = {};
  if (context.tenantId) headers["X-Tenant-ID"] = context.tenantId;
  if (context.userId) headers["X-User-ID"] = context.userId;
  if (context.roles?.length) headers["X-Roles"] = context.roles.join(",");
  return headers;
}

function retryableFor(status, code) {
  return status === 408 || status === 429 || status >= 500 || code === "EXTERNAL_SYSTEM_ERROR";
}

function errorPayload(body) {
  const source = body?.detail && typeof body.detail === "object" ? body.detail : body;
  return typeof source === "object" && source !== null ? source : {};
}

function apiErrorFromResponse(body, status, requestId) {
  const payload = errorPayload(body);
  const code = payload.code ?? "HTTP_ERROR";
  const message = payload.message ?? "Request failed";
  const details = payload.details && typeof payload.details === "object" ? payload.details : {};
  const errorRequestId = payload.request_id ?? requestId ?? null;
  return new FoundryLiteApiError(status, code, message, details, errorRequestId, retryableFor(status, code));
}

export function normalizeFoundryLiteError(error) {
  if (error instanceof FoundryLiteApiError) return error;
  if (error?.name === "FoundryLiteApiError") return error;
  const message = error?.message ?? "Network request failed";
  return new FoundryLiteApiError(0, "NETWORK_ERROR", message, {}, null, true);
}

export function isRetryableFoundryLiteError(error) {
  return Boolean(normalizeFoundryLiteError(error).retryable);
}

export function expectedObjectVersion(object) {
  return object.objectVersion;
}

export function createFoundryLiteClient(options) {
  async function request(path, init = {}) {
    const fetcher = options.fetchImpl ?? fetch;
    const { requestId: explicitRequestId, ...requestInit } = init;
    const requestId = explicitRequestId ?? options.requestIdFactory?.() ?? createRequestId("sdk");
    const response = await fetcher(`${options.baseUrl}${path}`, {
      ...requestInit,
      headers: {
        ...requestContextHeaders(options.context ?? {}),
        "X-Request-ID": requestId,
        ...(options.token ? { Authorization: `Bearer ${options.token}` } : {}),
        ...(options.headers ?? {}),
        ...(requestInit.headers ?? {}),
      },
    });
    const body = await response.json().catch(() => ({}));
    const responseRequestId = response.headers.get("X-Request-ID") ?? requestId;
    if (!response.ok) {
      const error = apiErrorFromResponse(body, response.status, responseRequestId);
      options.onResponse?.({
        path,
        status: response.status,
        ok: false,
        requestId: error.requestId,
        errorCode: error.code,
        retryable: error.retryable,
      });
      throw error;
    }
    options.onResponse?.({ path, status: response.status, ok: true, requestId: responseRequestId });
    return body;
  }

  return {
    request,
    objects: {
      Order: {
        get: (id, requestOptions = {}) => {
          const suffix = requestOptions.explain ? '?explain=true' : '';
          return request(`/api/objects/Order/${encodeURIComponent(id)}${suffix}`);
        },
        query: (payload = {}) => request(`/api/objects/Order/query`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        }),
      },
      Customer: {
        get: (id, requestOptions = {}) => {
          const suffix = requestOptions.explain ? '?explain=true' : '';
          return request(`/api/objects/Customer/${encodeURIComponent(id)}${suffix}`);
        },
        query: (payload = {}) => request(`/api/objects/Customer/query`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        }),
      },
    },
    actions: {
      ApproveOrder: {
        apply: (payload) => request(`/api/actions/ApproveOrder/apply`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Idempotency-Key": payload.idempotencyKey ?? idempotencyKey("ApproveOrder", payload.objectId),
          },
          body: JSON.stringify({
            target: { objectType: "Order", objectId: payload.objectId },
            expectedObjectVersion: payload.expectedObjectVersion,
            params: payload.params,
          }),
        }),
      },
    },
    operations: {
      backupRestore: {
        preflight: (payload = {}) => request(`/api/operations/backup-restore/preflight`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        }),
        startRestoreMode: (payload = {}) => request(`/api/operations/backup-restore/restore-mode/start`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        }),
        restoreModeStatus: (restoreId) => request(
          `/api/operations/backup-restore/restore-mode/${encodeURIComponent(restoreId)}`,
        ),
        approveResume: (restoreId, payload = {}) => request(
          `/api/operations/backup-restore/restore-mode/${encodeURIComponent(restoreId)}/approve-resume`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          },
        ),
      },
      deadLetterRecords: {
        list: (filters = {}) => {
          const suffix = filters.status ? `?status=${encodeURIComponent(filters.status)}` : '';
          return request(`/api/operations/dead-letter-records${suffix}`);
        },
        get: (id) => request(`/api/operations/dead-letter-records/${encodeURIComponent(id)}`),
        retry: (id, requestOptions) => request(
          `/api/operations/dead-letter-records/${encodeURIComponent(id)}/retry`,
          {
            method: "POST",
            headers: { "Idempotency-Key": requestOptions.idempotencyKey },
          },
        ),
        bulkRetry: (ids, requestOptions) => request(`/api/operations/dead-letter-records/bulk-retry`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Idempotency-Key": requestOptions.idempotencyKey,
          },
          body: JSON.stringify({ ids }),
        }),
        discard: (id) => request(
          `/api/operations/dead-letter-records/${encodeURIComponent(id)}/discard`,
          { method: "POST" },
        ),
      },
      icebergMaintenance: {
        plan: (datasetRef, options = {}) => {
          const params = new URLSearchParams();
          if (options.branch) params.set('branch', options.branch);
          if (options.smallFileThresholdBytes !== undefined) {
            params.set('smallFileThresholdBytes', String(options.smallFileThresholdBytes));
          }
          if (options.fileCountThreshold !== undefined) {
            params.set('fileCountThreshold', String(options.fileCountThreshold));
          }
          if (options.readAmplificationThreshold !== undefined) {
            params.set('readAmplificationThreshold', String(options.readAmplificationThreshold));
          }
          if (options.retentionMinSnapshots !== undefined) {
            params.set('retentionMinSnapshots', String(options.retentionMinSnapshots));
          }
          const suffix = params.toString() ? `?${params.toString()}` : '';
          return request(
            `/api/operations/maintenance/iceberg/${encodeURIComponent(datasetRef)}/plan${suffix}`,
            { method: "POST" },
          );
        },
      },
      observability: {
        detect: (payload) => request(`/api/operations/observability/detect`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        }),
      },
      reconciliation: {
        resolve: (writebackId, payload) => request(
          `/api/operations/reconciliation/${encodeURIComponent(writebackId)}/resolve`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          },
        ),
      },
      workflows: {
        startConnectorSync: (payload, requestOptions) =>
          request(`/api/operations/workflows/connector-sync/start`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "Idempotency-Key": requestOptions.idempotencyKey,
            },
            body: JSON.stringify(payload),
          }),
        get: (workflowRunId) =>
          request(`/api/operations/workflows/${encodeURIComponent(workflowRunId)}`),
      },
    },
  };
}
