// generated by scripts/generate_sdk_ts.py; do not edit by hand
export const ONTOLOGY_CONTRACT_FINGERPRINT = "a622ceca207f76d4";
export const SDK_CLIENT_SURFACE = {"actions":{"ApproveOrder":["apply"]},"aip":{"agent":["run"],"builder":["validate","run"]},"datasets":["list","versions","preview","inspect"],"helpers":["actionLockKey","classifyFoundryLiteError","collectCursorPages","createInFlightActionLock","createFoundryLiteClient","createRequestId","expectedObjectVersion","idempotencyKey","isRetryableFoundryLiteError","normalizeFoundryLiteError","requestContextHeaders","retryWithBackoff"],"insights":{"reviews":["list","create","get","assign","decide"]},"materializations":["run"],"objectSets":["list","create","get"],"objects":{"Customer":["get","query"],"Order":["get","query"],"generic":["get","query","links"]},"ontology":["catalog","validate"],"operations":{"backupRestore":["preflight","startRestoreMode","restoreModeStatus","approveResume"],"deadLetterEvents":["retry"],"deadLetterRecords":["list","get","retry","bulkRetry","discard"],"icebergMaintenance":["planReadOnly","plan"],"index":["replayObjectType","replayFailedRun"],"lineage":["get"],"observability":["detect"],"reconciliation":["resolve"],"runs":["list","detail","promptArtifact"],"transforms":["retry"],"workflows":["startConnectorSync","get"]},"system":["health"]};

export function idempotencyKey(actionName, objectId) {
  return `${actionName}-${objectId}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

export function createRequestId(scope = "sdk") {
  return `${scope}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

export class FoundryLiteApiError extends Error {
  constructor(status, code, message, details, requestId, retryable) {
    super(message);
    this.name = "FoundryLiteApiError";
    this.status = status;
    this.code = code;
    this.details = details;
    this.requestId = requestId;
    this.retryable = retryable;
  }
}

export function requestContextHeaders(context = {}) {
  const headers = {};
  if (context.tenantId) headers["X-Tenant-ID"] = context.tenantId;
  if (context.userId) headers["X-User-ID"] = context.userId;
  if (context.roles?.length) headers["X-Roles"] = context.roles.join(",");
  return headers;
}

function requireIdempotencyKey(value, operationName) {
  if (value) return value;
  throw new FoundryLiteApiError(
    0,
    "MISSING_IDEMPOTENCY_KEY",
    `${operationName} requires a caller-supplied idempotency key`,
    { operationName },
    null,
    false,
  );
}

function retryableFor(status, code) {
  return status === 408 || status === 429 || status >= 500 || code === "EXTERNAL_SYSTEM_ERROR";
}

function errorPayload(body) {
  const source = body?.detail && typeof body.detail === "object" ? body.detail : body;
  return typeof source === "object" && source !== null ? source : {};
}

function apiErrorFromResponse(body, status, requestId) {
  const payload = errorPayload(body);
  const code = payload.code ?? "HTTP_ERROR";
  const message = payload.message ?? "Request failed";
  const details = payload.details && typeof payload.details === "object" ? payload.details : {};
  const errorRequestId = payload.request_id ?? requestId ?? null;
  return new FoundryLiteApiError(status, code, message, details, errorRequestId, retryableFor(status, code));
}

export function normalizeFoundryLiteError(error) {
  if (error instanceof FoundryLiteApiError) return error;
  if (error?.name === "FoundryLiteApiError") return error;
  const message = error?.message ?? "Network request failed";
  return new FoundryLiteApiError(0, "NETWORK_ERROR", message, {}, null, true);
}

export function isRetryableFoundryLiteError(error) {
  return Boolean(normalizeFoundryLiteError(error).retryable);
}

export function expectedObjectVersion(object) {
  return object.objectVersion;
}

export function classifyFoundryLiteError(error) {
  const normalized = normalizeFoundryLiteError(error);
  let kind = 'unknown';
  if (normalized.code === "PERMISSION_DENIED") kind = "permission_denied";
  else if (normalized.code === "NOT_FOUND") kind = "not_found";
  else if (normalized.code === "VALIDATION_FAILED") kind = "validation";
  else if (normalized.code === 'CONFLICT' && _looksLikeStaleObjectVersion(normalized)) {
    kind = 'stale_object_version';
  } else if (normalized.code === "CONFLICT") kind = "conflict";
  else if (normalized.retryable) kind = "retryable";
  return {
    kind,
    status: normalized.status,
    code: normalized.code,
    message: normalized.message,
    details: normalized.details,
    requestId: normalized.requestId,
    retryable: normalized.retryable,
  };
}

function _looksLikeStaleObjectVersion(error) {
  return Boolean(
    error.details?.expectedObjectVersion !== undefined ||
      error.details?.actualObjectVersion !== undefined ||
      error.details?.objectVersion !== undefined ||
      error.message.toLowerCase().includes('object version')
  );
}

export function actionLockKey(actionName, objectId) {
  return `${actionName}:${objectId}`;
}

export function createInFlightActionLock() {
  const inFlight = new Map();
  return {
    run(key, task) {
      if (inFlight.has(key)) return inFlight.get(key);
      const promise = Promise.resolve().then(task).finally(() => {
        if (inFlight.get(key) === promise) inFlight.delete(key);
      });
      inFlight.set(key, promise);
      return promise;
    },
    isLocked(key) {
      return inFlight.has(key);
    },
    clear(key) {
      if (key === undefined) inFlight.clear();
      else inFlight.delete(key);
    },
  };
}

function defaultSleep(delayMs) {
  return new Promise((resolve) => setTimeout(resolve, delayMs));
}

function retryDelayMs(attempt, options) {
  const base = options.baseDelayMs ?? 250;
  const max = options.maxDelayMs ?? 4000;
  const jitterRatio = options.jitterRatio ?? 0.2;
  const exponential = Math.min(max, base * 2 ** Math.max(0, attempt - 1));
  const jitter = exponential * jitterRatio * Math.random();
  return Math.round(exponential + jitter);
}

export async function retryWithBackoff(operation, options = {}) {
  const maxAttempts = options.maxAttempts ?? 3;
  let attempt = 0;
  while (true) {
    try {
      return await operation();
    } catch (error) {
      attempt += 1;
      const normalized = normalizeFoundryLiteError(error);
      const shouldRetry = options.shouldRetry?.(normalized, attempt) ?? normalized.retryable;
      if (!shouldRetry || attempt >= maxAttempts) throw error;
      const delayMs = retryDelayMs(attempt, options);
      options.onRetry?.({ attempt, delayMs, error: normalized });
      await (options.sleep ?? defaultSleep)(delayMs);
    }
  }
}

export async function collectCursorPages(fetchPage, options = {}) {
  const getItems = options.getItems ?? ((page) => page.items ?? []);
  const getNextCursor = options.getNextCursor ?? ((page) => page.nextCursor ?? null);
  const maxPages = options.maxPages ?? 100;
  const items = [];
  let cursor = options.initialCursor ?? null;
  for (let pageNumber = 0; pageNumber < maxPages; pageNumber += 1) {
    const page = await fetchPage(cursor);
    items.push(...getItems(page));
    cursor = getNextCursor(page) ?? null;
    if (!cursor) return items;
  }
  throw new FoundryLiteApiError(
    0,
    "CURSOR_LIMIT_EXCEEDED",
    "Cursor pagination exceeded maxPages",
    { maxPages },
    null,
    false,
  );
}

export function createFoundryLiteClient(options) {
  async function request(path, init = {}) {
    const fetcher = options.fetchImpl ?? fetch;
    const { requestId: explicitRequestId, ...requestInit } = init;
    const requestId = explicitRequestId ?? options.requestIdFactory?.() ?? createRequestId("sdk");
    const response = await fetcher(`${options.baseUrl}${path}`, {
      ...requestInit,
      headers: {
        ...requestContextHeaders(options.context ?? {}),
        "X-Request-ID": requestId,
        ...(options.token ? { Authorization: `Bearer ${options.token}` } : {}),
        ...(options.headers ?? {}),
        ...(requestInit.headers ?? {}),
      },
    });
    const body = await response.json().catch(() => ({}));
    const responseRequestId = response.headers.get("X-Request-ID") ?? requestId;
    if (!response.ok) {
      const error = apiErrorFromResponse(body, response.status, responseRequestId);
      options.onResponse?.({
        path,
        status: response.status,
        ok: false,
        requestId: error.requestId,
        errorCode: error.code,
        retryable: error.retryable,
      });
      throw error;
    }
    options.onResponse?.({ path, status: response.status, ok: true, requestId: responseRequestId });
    return body;
  }

  return {
    request,
    system: {
      health: () => request(`/healthz`),
    },
    datasets: {
      list: () => request(`/api/datasets`),
      versions: (namespace, name) =>
        request(
          `/api/datasets/${encodeURIComponent(namespace)}/${encodeURIComponent(name)}/versions`,
        ),
      preview: (namespace, name, requestOptions = {}) => {
        const params = new URLSearchParams();
        if (requestOptions.limit !== undefined) params.set('limit', String(requestOptions.limit));
        const suffix = params.toString() ? `?${params.toString()}` : '';
        return request(
          `/api/datasets/${encodeURIComponent(namespace)}/${encodeURIComponent(name)}/preview${suffix}`,
        );
      },
      inspect: (namespace, name, requestOptions = {}) => {
        const params = new URLSearchParams();
        if (requestOptions.version !== undefined) params.set('version', String(requestOptions.version));
        const suffix = params.toString() ? `?${params.toString()}` : '';
        return request(
          `/api/datasets/${encodeURIComponent(namespace)}/${encodeURIComponent(name)}/inspect${suffix}`,
        );
      },
    },
    ontology: {
      catalog: () => request(`/api/ontology/catalog`),
      validate: (payload) => request(`/api/ontology/validate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      }),
    },
    insights: {
      reviews: {
        list: (filters = {}) => {
          const params = new URLSearchParams();
          if (filters.status) params.set('status', filters.status);
          if (filters.assigneeUserId) params.set('assigneeUserId', filters.assigneeUserId);
          if (filters.limit !== undefined) params.set('limit', String(filters.limit));
          const suffix = params.toString() ? `?${params.toString()}` : '';
          return request(`/api/insights/reviews${suffix}`);
        },
        create: (payload, options) => request(`/api/insights/reviews`, {
          method: "POST",
          headers: { "Content-Type": "application/json", "Idempotency-Key": requireIdempotencyKey(options?.idempotencyKey, "insights.reviews.create") },
          body: JSON.stringify(payload),
        }),
        get: (reviewId) => request(`/api/insights/reviews/${encodeURIComponent(reviewId)}`),
        assign: (reviewId, payload, options) => request(
          `/api/insights/reviews/${encodeURIComponent(reviewId)}/assign`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json", "Idempotency-Key": requireIdempotencyKey(options?.idempotencyKey, "insights.reviews.assign") },
            body: JSON.stringify(payload),
          },
        ),
        decide: (reviewId, payload, options) => request(
          `/api/insights/reviews/${encodeURIComponent(reviewId)}/decision`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json", "Idempotency-Key": requireIdempotencyKey(options?.idempotencyKey, "insights.reviews.decide") },
            body: JSON.stringify(payload),
          },
        ),
      },
    },
    objects: {
      generic: {
        get: (objectType, id, requestOptions = {}) => {
          const suffix = requestOptions.explain ? '?explain=true' : '';
          return request(
            `/api/objects/${encodeURIComponent(objectType)}/${encodeURIComponent(id)}${suffix}`,
          );
        },
        query: (objectType, payload = {}) => request(
          `/api/objects/${encodeURIComponent(objectType)}/query`,
          {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
          },
        ),
        links: (objectType, id, linkType) => request(
          `/api/objects/${encodeURIComponent(objectType)}/${encodeURIComponent(id)}` +
            `/links/${encodeURIComponent(linkType)}`,
        ),
      },
      Order: {
        get: (id, requestOptions = {}) => {
          const suffix = requestOptions.explain ? '?explain=true' : '';
          return request(`/api/objects/Order/${encodeURIComponent(id)}${suffix}`);
        },
        query: (payload = {}) => request(`/api/objects/Order/query`, {
          method: "POST",
          headers: { "Content-Type": "application/json", "X-Foundry-Lite-Object": "Order" },
          body: JSON.stringify(payload),
        }),
      },
      Customer: {
        get: (id, requestOptions = {}) => {
          const suffix = requestOptions.explain ? '?explain=true' : '';
          return request(`/api/objects/Customer/${encodeURIComponent(id)}${suffix}`);
        },
        query: (payload = {}) => request(`/api/objects/Customer/query`, {
          method: "POST",
          headers: { "Content-Type": "application/json", "X-Foundry-Lite-Object": "Customer" },
          body: JSON.stringify(payload),
        }),
      },
    },
    actions: {
      ApproveOrder: {
        apply: (payload) => request(`/api/actions/ApproveOrder/apply`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Idempotency-Key": requireIdempotencyKey(payload.idempotencyKey, "ApproveOrder"),
          },
          body: JSON.stringify({
            target: { objectType: "Order", objectId: payload.objectId },
            expectedObjectVersion: payload.expectedObjectVersion,
            params: payload.params,
          }),
        }),
      },
    },
    objectSets: {
      list: (filters = {}) => {
        const suffix = filters.objectType ? `?objectType=${encodeURIComponent(filters.objectType)}` : '';
        return request(`/api/object-sets${suffix}`);
      },
      create: (payload) => request(`/api/object-sets`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      }),
      get: (id) => request(`/api/object-sets/${encodeURIComponent(id)}`),
    },
    materializations: {
      run: (apiName) => request(
        `/api/materializations/${encodeURIComponent(apiName)}/run`,
        { method: "POST" },
      ),
    },
    aip: {
      builder: {
        validate: (payload) => request(`/api/aip/builder/validate`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        }),
        run: (payload) => request(`/api/aip/builder/run`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        }),
      },
      agent: {
        run: (payload) => request(`/api/aip/agent/run`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        }),
      },
    },
    operations: {
      runs: {
        list: (filters = {}) => {
          const params = new URLSearchParams();
          if (filters.runType) params.set('runType', String(filters.runType));
          if (filters.status) params.set('status', filters.status);
          if (filters.since) params.set('since', filters.since);
          if (filters.until) params.set('until', filters.until);
          if (filters.limit !== undefined) params.set('limit', String(filters.limit));
          if (filters.cursor) params.set('cursor', filters.cursor);
          const suffix = params.toString() ? `?${params.toString()}` : '';
          return request(`/api/operations/runs${suffix}`);
        },
        detail: (runType, runId) => request(
          `/api/operations/runs/${encodeURIComponent(runType)}/${encodeURIComponent(runId)}`,
        ),
        promptArtifact: (runId, artifactId) => request(
          `/api/operations/runs/ai/${encodeURIComponent(runId)}` +
            `/prompt-artifacts/${encodeURIComponent(artifactId)}`,
        ),
      },
      backupRestore: {
        preflight: (payload = {}) => request(`/api/operations/backup-restore/preflight`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        }),
        startRestoreMode: (payload = {}) => request(`/api/operations/backup-restore/restore-mode/start`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        }),
        restoreModeStatus: (restoreId) => request(
          `/api/operations/backup-restore/restore-mode/${encodeURIComponent(restoreId)}`,
        ),
        approveResume: (restoreId, payload = {}) => request(
          `/api/operations/backup-restore/restore-mode/${encodeURIComponent(restoreId)}/approve-resume`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          },
        ),
      },
      deadLetterRecords: {
        list: (filters = {}) => {
          const suffix = filters.status ? `?status=${encodeURIComponent(filters.status)}` : '';
          return request(`/api/operations/dead-letter-records${suffix}`);
        },
        get: (id) => request(`/api/operations/dead-letter-records/${encodeURIComponent(id)}`),
        retry: (id, requestOptions) => request(
          `/api/operations/dead-letter-records/${encodeURIComponent(id)}/retry`,
          {
            method: "POST",
            headers: { "Idempotency-Key": requireIdempotencyKey(requestOptions?.idempotencyKey, "operations.deadLetterRecords.retry") },
          },
        ),
        bulkRetry: (ids, requestOptions) => request(`/api/operations/dead-letter-records/bulk-retry`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Idempotency-Key": requireIdempotencyKey(requestOptions?.idempotencyKey, "operations.deadLetterRecords.bulkRetry"),
          },
          body: JSON.stringify({ ids }),
        }),
        discard: (id) => request(
          `/api/operations/dead-letter-records/${encodeURIComponent(id)}/discard`,
          { method: "POST" },
        ),
      },
      deadLetterEvents: {
        retry: (id) => request(
          `/api/operations/dead-letter-events/${encodeURIComponent(id)}/retry`,
          { method: "POST" },
        ),
      },
      icebergMaintenance: {
        planReadOnly: (datasetRef, options = {}) => {
          const params = new URLSearchParams();
          params.set('datasetRef', datasetRef);
          if (options.branch) params.set('branch', options.branch);
          if (options.smallFileThresholdBytes !== undefined) {
            params.set('smallFileThresholdBytes', String(options.smallFileThresholdBytes));
          }
          if (options.fileCountThreshold !== undefined) {
            params.set('fileCountThreshold', String(options.fileCountThreshold));
          }
          if (options.readAmplificationThreshold !== undefined) {
            params.set('readAmplificationThreshold', String(options.readAmplificationThreshold));
          }
          if (options.retentionMinSnapshots !== undefined) {
            params.set('retentionMinSnapshots', String(options.retentionMinSnapshots));
          }
          return request(`/api/operations/maintenance/iceberg?${params.toString()}`);
        },
        plan: (datasetRef, options = {}) => {
          const params = new URLSearchParams();
          if (options.branch) params.set('branch', options.branch);
          if (options.smallFileThresholdBytes !== undefined) {
            params.set('smallFileThresholdBytes', String(options.smallFileThresholdBytes));
          }
          if (options.fileCountThreshold !== undefined) {
            params.set('fileCountThreshold', String(options.fileCountThreshold));
          }
          if (options.readAmplificationThreshold !== undefined) {
            params.set('readAmplificationThreshold', String(options.readAmplificationThreshold));
          }
          if (options.retentionMinSnapshots !== undefined) {
            params.set('retentionMinSnapshots', String(options.retentionMinSnapshots));
          }
          const suffix = params.toString() ? `?${params.toString()}` : '';
          return request(
            `/api/operations/maintenance/iceberg/${encodeURIComponent(datasetRef)}/plan${suffix}`,
            { method: "POST" },
          );
        },
      },
      index: {
        replayObjectType: (objectType) => request(
          `/api/operations/index/${encodeURIComponent(objectType)}/replay`,
          { method: "POST" },
        ),
        replayFailedRun: (runId) => request(
          `/api/operations/runs/index/${encodeURIComponent(runId)}/replay`,
          { method: "POST" },
        ),
      },
      lineage: {
        get: (resourceId) => {
          const params = new URLSearchParams();
          params.set('resourceId', resourceId);
          return request(`/api/operations/lineage?${params.toString()}`);
        },
      },
      observability: {
        detect: (payload) => request(`/api/operations/observability/detect`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        }),
      },
      reconciliation: {
        resolve: (writebackId, payload) => request(
          `/api/operations/reconciliation/${encodeURIComponent(writebackId)}/resolve`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          },
        ),
      },
      transforms: {
        retry: (runId) => request(
          `/api/operations/runs/transform/${encodeURIComponent(runId)}/retry`,
          { method: "POST" },
        ),
      },
      workflows: {
        startConnectorSync: (payload, requestOptions) =>
          request(`/api/operations/workflows/connector-sync/start`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "Idempotency-Key": requireIdempotencyKey(requestOptions?.idempotencyKey, "operations.workflows.startConnectorSync"),
            },
            body: JSON.stringify(payload),
          }),
        get: (workflowRunId) =>
          request(`/api/operations/workflows/${encodeURIComponent(workflowRunId)}`),
      },
    },
  };
}
