// generated by scripts/generate_sdk_ts.py; do not edit by hand
export const ONTOLOGY_CONTRACT_FINGERPRINT = "a622ceca207f76d4";
export const SDK_CLIENT_SURFACE = {"actions":{"ApproveOrder":["apply"]},"helpers":["createFoundryLiteClient","expectedObjectVersion","idempotencyKey"],"objects":{"Customer":["get","query"],"Order":["get","query"]}};

export function idempotencyKey(actionName, objectId) {
  return `${actionName}-${objectId}-${Date.now()}`;
}

export function expectedObjectVersion(object) {
  return object.objectVersion;
}

export function createFoundryLiteClient(options) {
  async function request(path, init = {}) {
    const fetcher = options.fetchImpl ?? fetch;
    const response = await fetcher(`${options.baseUrl}${path}`, {
      ...init,
      headers: {
        ...(options.token ? { Authorization: `Bearer ${options.token}` } : {}),
        ...(options.headers ?? {}),
        ...(init.headers ?? {}),
      },
    });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw body;
    }
    return body;
  }

  return {
    objects: {
      Order: {
        get: (id, requestOptions = {}) => {
          const suffix = requestOptions.explain ? '?explain=true' : '';
          return request(`/api/objects/Order/${encodeURIComponent(id)}${suffix}`);
        },
        query: (payload = {}) => request(`/api/objects/Order/query`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        }),
      },
      Customer: {
        get: (id, requestOptions = {}) => {
          const suffix = requestOptions.explain ? '?explain=true' : '';
          return request(`/api/objects/Customer/${encodeURIComponent(id)}${suffix}`);
        },
        query: (payload = {}) => request(`/api/objects/Customer/query`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        }),
      },
    },
    actions: {
      ApproveOrder: {
        apply: (payload) => request(`/api/actions/ApproveOrder/apply`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Idempotency-Key": payload.idempotencyKey ?? idempotencyKey("ApproveOrder", payload.objectId),
          },
          body: JSON.stringify({
            target: { objectType: "Order", objectId: payload.objectId },
            expectedObjectVersion: payload.expectedObjectVersion,
            params: payload.params,
          }),
        }),
      },
    },
  };
}
