"""Browser OSDK registry, ontology index, constants, and runtime template lines."""

from __future__ import annotations

import json
from collections.abc import Sequence

from scripts.sdk_generator.ontology import ActionDef, InterfaceDef, LinkDef, ObjectDef, OntologyDef
from scripts.sdk_generator.surface import (
    _action_alias_entries,
    _link_entries_for_object,
    _object_link_alias,
    _primary_key_property,
)


def _web_api_names_csv(items: Sequence[ActionDef | InterfaceDef | LinkDef | ObjectDef]) -> str:
    return ", ".join(item.api_name for item in items)


def _web_api_name_values_csv(items: Sequence[ActionDef | InterfaceDef | LinkDef | ObjectDef]) -> str:
    return ", ".join(json.dumps(item.api_name) for item in items)


def _web_osdk_registry_lines(ontology: OntologyDef) -> list[str]:
    lines: list[str] = []
    for object_def in ontology.objects:
        lines.extend(_web_osdk_object_constant_lines(object_def))
    object_names = _web_api_names_csv(ontology.objects)
    object_name_values = _web_api_name_values_csv(ontology.objects)
    lines.append(f"export const $Objects = Object.freeze({{ {object_names} }});")
    for interface_def in ontology.interfaces:
        lines.extend(_web_osdk_interface_constant_lines(interface_def))
    interface_names = _web_api_names_csv(ontology.interfaces)
    interface_name_values = _web_api_name_values_csv(ontology.interfaces)
    for link_def in ontology.links:
        lines.extend(_web_osdk_link_constant_lines(link_def))
    link_names = _web_api_names_csv(ontology.links)
    link_name_values = _web_api_name_values_csv(ontology.links)
    for action_def in ontology.actions:
        lines.extend(_web_osdk_action_constant_lines(action_def))
    action_names = _web_api_names_csv(ontology.actions)
    action_name_values = _web_api_name_values_csv(ontology.actions)
    lines.extend(
        [
            f"export const $Interfaces = Object.freeze({{ {interface_names} }});",
            f"export const $Links = Object.freeze({{ {link_names} }});",
            f"export const $Actions = Object.freeze({{ {action_names} }});",
            "export const $Ontology = Object.freeze({",
            "  objects: $Objects,",
            "  interfaces: $Interfaces,",
            "  links: $Links,",
            "  actions: $Actions,",
            f"  objectApiNames: Object.freeze([{object_name_values}]),",
            f"  interfaceApiNames: Object.freeze([{interface_name_values}]),",
            f"  linkApiNames: Object.freeze([{link_name_values}]),",
            f"  actionApiNames: Object.freeze([{action_name_values}]),",
            "});",
            "",
            "export function getObjectType(apiName) {",
            "  const objectType = $Objects[apiName];",
            "  if (!objectType) {",
            "    throw new FoundryLiteApiError(",
            "      0,",
            '      "UNKNOWN_OSDK_OBJECT",',
            "      `Unknown OSDK object ${String(apiName)}`,",
            "      { objectApiName: String(apiName) },",
            "      null,",
            "      false,",
            "    );",
            "  }",
            "  return objectType;",
            "}",
            "",
            "export function getActionType(apiName) {",
            "  const actionType = $Actions[apiName];",
            "  if (!actionType) {",
            "    throw new FoundryLiteApiError(",
            "      0,",
            '      "UNKNOWN_OSDK_ACTION",',
            "      `Unknown OSDK action ${String(apiName)}`,",
            "      { actionApiName: String(apiName) },",
            "      null,",
            "      false,",
            "    );",
            "  }",
            "  return actionType;",
            "}",
            "",
        ]
    )
    lines.extend(_web_osdk_generated_relation_lines(ontology))
    lines.extend(_web_ontology_index_lines())
    return lines


def _web_osdk_generated_relation_lines(ontology: OntologyDef) -> list[str]:
    return [
        *_web_osdk_link_entries_lines(ontology),
        *_web_osdk_action_entries_lines(ontology),
    ]


def _web_osdk_link_entries_lines(ontology: OntologyDef) -> list[str]:
    lines = [
        "function osdkLinkEntries(objectType) {",
        "  switch (objectType.apiName) {",
    ]
    for object_def in ontology.objects:
        entries = _link_entries_for_object(ontology.links, object_def.api_name)
        lines.append(f"    case '{object_def.api_name}':")
        if entries:
            lines.append("      return [")
            for alias, link_def, target_object in entries:
                entry = f"{{ alias: '{alias}', linkType: '{link_def.api_name}', targetObjectType: {target_object} }}"
                lines.append(f"        {entry},")
            lines.append("      ];")
        else:
            lines.append("      return [];")
    lines.extend(["    default:", "      return [];", "  }", "}", ""])
    return lines


def _web_osdk_action_entries_lines(ontology: OntologyDef) -> list[str]:
    lines = [
        "function osdkActionEntries(objectType) {",
        "  switch (objectType.apiName) {",
    ]
    for object_def in ontology.objects:
        actions = [action for action in ontology.actions if action.target == object_def.api_name]
        lines.append(f"    case '{object_def.api_name}':")
        if actions:
            lines.append("      return [")
            for alias, action_def in _action_alias_entries(actions):
                lines.append(f"        {{ alias: '{alias}', actionType: {action_def.api_name} }},")
            lines.append("      ];")
        else:
            lines.append("      return [];")
    lines.extend(["    default:", "      return [];", "  }", "}", ""])
    return lines


def _web_ontology_index_lines() -> list[str]:
    return [
        "export function sdkPackageManifest() {",
        "  return SDK_PACKAGE_MANIFEST;",
        "}",
        "",
        "function sortedOntologyApiNames(values) {",
        "  return Array.from(new Set(values)).sort((left, right) => left.localeCompare(right));",
        "}",
        "",
        "function ontologyApiNameDifference(left, right) {",
        "  const rightNames = new Set(right);",
        "  return left.filter((apiName) => !rightNames.has(apiName));",
        "}",
        "",
        "function ontologyCatalogFingerprint(catalog = null) {",
        "  const value = catalog?.ontologyContractFingerprint",
        "    ?? catalog?.contractFingerprint",
        "    ?? catalog?.fingerprint",
        "    ?? null;",
        "  return typeof value === 'string' && value.length > 0 ? value : null;",
        "}",
        "",
        "function ontologyCatalogActionApiNames(catalog) {",
        "  return sortedOntologyApiNames(",
        "    catalog.objectTypes.flatMap((objectType) => objectType.actions.map((action) => action.apiName)),",
        "  );",
        "}",
        "",
        "export function sdkOntologyDriftReport(catalog = null) {",
        "  const hasCatalog = catalog !== null && catalog !== undefined;",
        "  const expectedOntologyFingerprint = SDK_PACKAGE_MANIFEST.ontologyFingerprint;",
        "  const actualOntologyFingerprint = ontologyCatalogFingerprint(catalog);",
        "  const isFingerprintMatched = actualOntologyFingerprint === null",
        "    ? null",
        "    : actualOntologyFingerprint === expectedOntologyFingerprint;",
        "  const generatedObjectApiNames = [...SDK_PACKAGE_MANIFEST.objectApiNames];",
        "  const generatedActionApiNames = [...SDK_PACKAGE_MANIFEST.actionApiNames];",
        "  const generatedLinkApiNames = [...SDK_PACKAGE_MANIFEST.linkApiNames];",
        "  const liveObjectApiNames = hasCatalog",
        "    ? sortedOntologyApiNames(catalog.objectTypes.map((objectType) => objectType.apiName))",
        "    : [];",
        "  const liveActionApiNames = hasCatalog ? ontologyCatalogActionApiNames(catalog) : [];",
        "  const liveLinkApiNames = hasCatalog",
        "    ? sortedOntologyApiNames(catalog.linkTypes.map((linkType) => linkType.apiName))",
        "    : [];",
        "  const dynamicOnlyObjectApiNames = hasCatalog",
        "    ? ontologyApiNameDifference(liveObjectApiNames, generatedObjectApiNames)",
        "    : [];",
        "  const staticOnlyObjectApiNames = hasCatalog",
        "    ? ontologyApiNameDifference(generatedObjectApiNames, liveObjectApiNames)",
        "    : [];",
        "  const dynamicOnlyActionApiNames = hasCatalog",
        "    ? ontologyApiNameDifference(liveActionApiNames, generatedActionApiNames)",
        "    : [];",
        "  const staticOnlyActionApiNames = hasCatalog",
        "    ? ontologyApiNameDifference(generatedActionApiNames, liveActionApiNames)",
        "    : [];",
        "  const dynamicOnlyLinkApiNames = hasCatalog",
        "    ? ontologyApiNameDifference(liveLinkApiNames, generatedLinkApiNames)",
        "    : [];",
        "  const staticOnlyLinkApiNames = hasCatalog",
        "    ? ontologyApiNameDifference(generatedLinkApiNames, liveLinkApiNames)",
        "    : [];",
        "  const reasonCodes = [];",
        "  if (isFingerprintMatched === false) reasonCodes.push('ONTOLOGY_FINGERPRINT_MISMATCH');",
        "  if (dynamicOnlyObjectApiNames.length > 0) reasonCodes.push('DYNAMIC_OBJECT_TYPES');",
        "  if (staticOnlyObjectApiNames.length > 0) reasonCodes.push('STATIC_OBJECT_TYPES');",
        "  if (dynamicOnlyActionApiNames.length > 0) reasonCodes.push('DYNAMIC_ACTION_TYPES');",
        "  if (staticOnlyActionApiNames.length > 0) reasonCodes.push('STATIC_ACTION_TYPES');",
        "  if (dynamicOnlyLinkApiNames.length > 0) reasonCodes.push('DYNAMIC_LINK_TYPES');",
        "  if (staticOnlyLinkApiNames.length > 0) reasonCodes.push('STATIC_LINK_TYPES');",
        "  const requiresSdkRegeneration = hasCatalog && reasonCodes.length > 0;",
        "  return {",
        "    manifest: SDK_PACKAGE_MANIFEST,",
        "    expectedOntologyFingerprint,",
        "    actualOntologyFingerprint,",
        "    isFingerprintMatched,",
        "    generatedObjectApiNames,",
        "    liveObjectApiNames,",
        "    dynamicOnlyObjectApiNames,",
        "    staticOnlyObjectApiNames,",
        "    generatedActionApiNames,",
        "    liveActionApiNames,",
        "    dynamicOnlyActionApiNames,",
        "    staticOnlyActionApiNames,",
        "    generatedLinkApiNames,",
        "    liveLinkApiNames,",
        "    dynamicOnlyLinkApiNames,",
        "    staticOnlyLinkApiNames,",
        "    requiresSdkRegeneration,",
        "    reasonCodes,",
        "    regenerationHint: requiresSdkRegeneration",
        "      ? 'Regenerate the Foundry-lite OSDK package from the active Ontology before using these resources.'",
        "      : hasCatalog",
        "        ? 'Generated OSDK package matches the provided ontology catalog.'",
        "        : 'No live ontology catalog was provided; compare against client.ontology.catalog() before release.',",
        "  };",
        "}",
        "",
        "export function assertFoundryLiteSdkFresh(catalog = null) {",
        "  const report = sdkOntologyDriftReport(catalog);",
        "  if (report.requiresSdkRegeneration) {",
        "    throw new FoundryLiteApiError(",
        "      0,",
        "      'OSDK_SDK_REGENERATION_REQUIRED',",
        "      'Generated Foundry-lite OSDK package is stale for the provided ontology catalog.',",
        "      { report },",
        "      null,",
        "      false,",
        "    );",
        "  }",
        "  return report;",
        "}",
        "",
        "function readOntologyIndexGeneratedObjectType(apiName) {",
        "  try {",
        "    return getObjectType(apiName);",
        "  } catch {",
        "    return null;",
        "  }",
        "}",
        "",
        "function readOntologyIndexGeneratedActionType(apiName) {",
        "  try {",
        "    return getActionType(apiName);",
        "  } catch {",
        "    return null;",
        "  }",
        "}",
        "",
        "function ontologyIndexSearchText(parts) {",
        "  return parts.filter(Boolean).join(' ').toLowerCase();",
        "}",
        "",
        "function ontologyIndexMatches(searchText, query) {",
        "  const terms = query.trim().toLowerCase().split(/\\s+/).filter(Boolean);",
        "  if (terms.length === 0) return true;",
        "  return terms.every((term) => searchText.includes(term));",
        "}",
        "",
        "function ontologyIndexActionView(action, generatedActionType, apiName, targetObjectType) {",
        "  const displayName = action?.displayName ?? apiName;",
        "  return {",
        "    apiName,",
        "    displayName,",
        "    targetObjectType,",
        "    enabled: action?.enabled ?? true,",
        "    catalogAction: action,",
        "    generatedActionType,",
        "    isGeneratedActionTypeAvailable: generatedActionType !== null,",
        "    searchText: ontologyIndexSearchText([apiName, displayName, targetObjectType]),",
        "  };",
        "}",
        "",
        "function ontologyIndexObjectView(objectType, generatedObjectType, apiName, actions) {",
        "  const properties = objectType?.properties ?? [];",
        "  const propertyNames = properties.length > 0",
        "    ? properties.map((property) => property.apiName)",
        "    : [...(generatedObjectType?.properties ?? [])];",
        "  const searchablePropertyNames = properties",
        "    .filter((property) => property.searchable)",
        "    .map((property) => property.apiName);",
        "  const editablePropertyNames = properties",
        "    .filter((property) => property.editable)",
        "    .map((property) => property.apiName);",
        "  const classifiedPropertyNames = properties",
        "    .filter((property) => property.classification !== null)",
        "    .map((property) => property.apiName);",
        "  const displayName = objectType?.displayName ?? apiName;",
        "  const description = objectType?.description ?? null;",
        "  return {",
        "    apiName,",
        "    displayName,",
        "    description,",
        "    primaryKeyProperty: objectType?.primaryKeyProperty ?? generatedObjectType?.primaryKey ?? 'id',",
        "    propertyNames,",
        "    searchablePropertyNames,",
        "    editablePropertyNames,",
        "    classifiedPropertyNames,",
        "    catalogObject: objectType,",
        "    generatedObjectType,",
        "    isGeneratedObjectTypeAvailable: generatedObjectType !== null,",
        "    actions,",
        "    actionCount: actions.length,",
        "    propertyCount: propertyNames.length,",
        "    searchText: ontologyIndexSearchText([",
        "      apiName,",
        "      displayName,",
        "      description,",
        "      propertyNames.join(' '),",
        "      actions.map((action) => action.apiName).join(' '),",
        "    ]),",
        "  };",
        "}",
        "",
        "function groupOntologyIndexActions(actionViews) {",
        "  const grouped = {};",
        "  for (const actionView of actionViews) {",
        "    grouped[actionView.targetObjectType] ??= [];",
        "    grouped[actionView.targetObjectType].push(actionView);",
        "  }",
        "  return grouped;",
        "}",
        "",
        "export function createFoundryLiteOntologyIndex(catalog = null) {",
        "  const actionViewsByApiName = {};",
        "  for (const objectType of catalog?.objectTypes ?? []) {",
        "    for (const action of objectType.actions) {",
        "      actionViewsByApiName[action.apiName] = ontologyIndexActionView(",
        "        action,",
        "        readOntologyIndexGeneratedActionType(action.apiName),",
        "        action.apiName,",
        "        action.target,",
        "      );",
        "    }",
        "  }",
        "  for (const apiName of $Ontology.actionApiNames) {",
        "    if (actionViewsByApiName[apiName]) continue;",
        "    const generatedActionType = getActionType(apiName);",
        "    actionViewsByApiName[apiName] = ontologyIndexActionView(",
        "      null,",
        "      generatedActionType,",
        "      apiName,",
        "      generatedActionType.targetObjectType,",
        "    );",
        "  }",
        "  const actionViews = Object.values(actionViewsByApiName)",
        "    .sort((left, right) => left.apiName.localeCompare(right.apiName));",
        "  const actionsByTargetObjectApiName = groupOntologyIndexActions(actionViews);",
        "  const objectViewsByApiName = {};",
        "  for (const objectType of catalog?.objectTypes ?? []) {",
        "    objectViewsByApiName[objectType.apiName] = ontologyIndexObjectView(",
        "      objectType,",
        "      readOntologyIndexGeneratedObjectType(objectType.apiName),",
        "      objectType.apiName,",
        "      actionsByTargetObjectApiName[objectType.apiName] ?? [],",
        "    );",
        "  }",
        "  for (const apiName of $Ontology.objectApiNames) {",
        "    if (objectViewsByApiName[apiName]) continue;",
        "    objectViewsByApiName[apiName] = ontologyIndexObjectView(",
        "      null,",
        "      getObjectType(apiName),",
        "      apiName,",
        "      actionsByTargetObjectApiName[apiName] ?? [],",
        "    );",
        "  }",
        "  const objectViews = Object.values(objectViewsByApiName)",
        "    .sort((left, right) => left.apiName.localeCompare(right.apiName));",
        "  return {",
        "    catalog: catalog ?? null,",
        "    objectViews,",
        "    actionViews,",
        "    objectViewsByApiName,",
        "    actionViewsByApiName,",
        "    actionsByTargetObjectApiName,",
        "    generatedObjectViews: objectViews.filter((view) => view.isGeneratedObjectTypeAvailable),",
        "    dynamicOnlyObjectViews: objectViews.filter((view) => view.catalogObject && !view.generatedObjectType),",
        "    staticOnlyObjectViews: objectViews.filter((view) => !view.catalogObject && view.generatedObjectType),",
        "    generatedActionViews: actionViews.filter((view) => view.isGeneratedActionTypeAvailable),",
        "    dynamicOnlyActionViews: actionViews.filter((view) => view.catalogAction && !view.generatedActionType),",
        "    staticOnlyActionViews: actionViews.filter((view) => !view.catalogAction && view.generatedActionType),",
        "    objectCount: objectViews.length,",
        "    actionCount: actionViews.length,",
        "    hasDynamicOnlyTypes: objectViews.some((view) => view.catalogObject && !view.generatedObjectType)",
        "      || actionViews.some((view) => view.catalogAction && !view.generatedActionType),",
        "    hasStaticOnlyTypes: objectViews.some((view) => !view.catalogObject && view.generatedObjectType)",
        "      || actionViews.some((view) => !view.catalogAction && view.generatedActionType),",
        "    getObjectView(apiName) {",
        "      const objectView = objectViewsByApiName[apiName];",
        "      if (!objectView) {",
        "        throw new FoundryLiteApiError(",
        "          0,",
        "          'UNKNOWN_ONTOLOGY_OBJECT_VIEW',",
        "          `Unknown ontology object ${apiName}`,",
        "          { objectApiName: apiName },",
        "          null,",
        "          false,",
        "        );",
        "      }",
        "      return objectView;",
        "    },",
        "    getActionView(apiName) {",
        "      const actionView = actionViewsByApiName[apiName];",
        "      if (!actionView) {",
        "        throw new FoundryLiteApiError(",
        "          0,",
        "          'UNKNOWN_ONTOLOGY_ACTION_VIEW',",
        "          `Unknown ontology action ${apiName}`,",
        "          { actionApiName: apiName },",
        "          null,",
        "          false,",
        "        );",
        "      }",
        "      return actionView;",
        "    },",
        "    actionsForObjectType(apiName) {",
        "      return actionsByTargetObjectApiName[apiName] ?? [];",
        "    },",
        "    findObjectTypes(query) {",
        "      return objectViews.filter((view) => ontologyIndexMatches(view.searchText, query));",
        "    },",
        "    findActionTypes(query) {",
        "      return actionViews.filter((view) => ontologyIndexMatches(view.searchText, query));",
        "    },",
        "  };",
        "}",
        "",
    ]


def _web_osdk_object_constant_lines(object_def: ObjectDef) -> list[str]:
    property_names = ", ".join(json.dumps(prop.api_name) for prop in object_def.properties)
    primary_key = json.dumps(_primary_key_property(object_def))
    title_property = json.dumps(object_def.title_property)
    return [
        f"export const {object_def.api_name} = Object.freeze({{",
        '  kind: "object",',
        f'  apiName: "{object_def.api_name}",',
        f"  primaryKey: {primary_key},",
        f"  titleProperty: {title_property},",
        f"  properties: Object.freeze([{property_names}]),",
        "});",
    ]


def _web_osdk_interface_constant_lines(interface_def: InterfaceDef) -> list[str]:
    property_names = ", ".join(json.dumps(prop.api_name) for prop in interface_def.properties)
    implementer_names = ", ".join(json.dumps(name) for name in interface_def.implementers)
    return [
        f"export const {interface_def.api_name} = Object.freeze({{",
        '  kind: "interface",',
        f'  apiName: "{interface_def.api_name}",',
        f"  properties: Object.freeze([{property_names}]),",
        f"  implementers: Object.freeze([{implementer_names}]),",
        "});",
    ]


def _web_osdk_link_constant_lines(link_def: LinkDef) -> list[str]:
    from_alias = json.dumps(_object_link_alias(link_def.to_object))
    to_alias = json.dumps(_object_link_alias(link_def.from_object))
    return [
        f"export const {link_def.api_name} = Object.freeze({{",
        '  kind: "link",',
        f'  apiName: "{link_def.api_name}",',
        f'  fromObjectType: "{link_def.from_object}",',
        f'  toObjectType: "{link_def.to_object}",',
        f"  fromAlias: {from_alias},",
        f"  toAlias: {to_alias},",
        "});",
    ]


def _web_osdk_action_constant_lines(action_def: ActionDef) -> list[str]:
    return [
        f"export const {action_def.api_name} = Object.freeze({{",
        '  kind: "action",',
        f'  apiName: "{action_def.api_name}",',
        f'  targetObjectType: "{action_def.target}",',
        "});",
    ]


def _web_osdk_runtime_lines() -> list[str]:
    return [
        "function isOsdkRecord(value) {",
        "  return typeof value === 'object' && value !== null && !Array.isArray(value);",
        "}",
        "",
        "function osdkValidationError(code, message, details) {",
        "  return new FoundryLiteApiError(0, code, message, details, null, false);",
        "}",
        "",
        "function requireOsdkProperty(objectType, property, source) {",
        "  if (!objectType.properties.includes(property)) {",
        "    const code = source === 'orderBy'",
        "      ? 'INVALID_OSDK_ORDER_PROPERTY'",
        "      : source === 'aggregate.groupBy'",
        "        ? 'INVALID_OSDK_AGGREGATE_GROUPBY_PROPERTY'",
        "        : 'INVALID_OSDK_FILTER_PROPERTY';",
        "    throw osdkValidationError(",
        "      code,",
        "      `OSDK ${source} references unknown property ${property} on ${objectType.apiName}`,",
        "      { objectType: objectType.apiName, property, source },",
        "    );",
        "  }",
        "}",
        "",
        "function normalizeLegacyOsdkFilter(objectType, filter) {",
        "  if ('and' in filter) {",
        "    const items = filter.and;",
        "    if (!Array.isArray(items)) {",
        "      throw osdkValidationError(",
        "        'INVALID_OSDK_FILTER',",
        "        'OSDK and filter must be an array',",
        "        { objectType: objectType.apiName },",
        "      );",
        "    }",
        "    return { and: items.map((item) => normalizeOsdkFilterInput(objectType, item)) };",
        "  }",
        "  if ('or' in filter) {",
        "    const items = filter.or;",
        "    if (!Array.isArray(items)) {",
        "      throw osdkValidationError(",
        "        'INVALID_OSDK_FILTER',",
        "        'OSDK or filter must be an array',",
        "        { objectType: objectType.apiName },",
        "      );",
        "    }",
        "    return { or: items.map((item) => normalizeOsdkFilterInput(objectType, item)) };",
        "  }",
        "  const property = filter.property;",
        "  if (typeof property !== 'string') {",
        "    throw osdkValidationError(",
        "      'INVALID_OSDK_FILTER',",
        "      'OSDK raw filter property must be a string',",
        "      { objectType: objectType.apiName },",
        "    );",
        "  }",
        "  requireOsdkProperty(objectType, property, 'filter');",
        "  return filter;",
        "}",
        "",
        "function normalizeOsdkPropertyOperator(objectType, property, operator, value) {",
        "  if (operator === '$eq') return { property, op: 'eq', value };",
        "  if (operator === '$in') {",
        "    if (!Array.isArray(value)) {",
        "      throw osdkValidationError('INVALID_OSDK_FILTER_VALUE', 'OSDK $in filter value must be an array', {",
        "        objectType: objectType.apiName,",
        "        property,",
        "        operator,",
        "      });",
        "    }",
        "    return { property, op: 'in', value: [...value] };",
        "  }",
        "  if (operator === '$gte') return { property, op: 'gte', value };",
        "  if (operator === '$lte') return { property, op: 'lte', value };",
        "  if (operator === '$contains') return { property, op: 'contains', value };",
        "  if (operator === '$isNull') {",
        "    if (value !== true) {",
        "      throw osdkValidationError(",
        "        'INVALID_OSDK_FILTER_VALUE',",
        "        'Only OSDK $isNull: true is supported by this backend slice',",
        "        {",
        "        objectType: objectType.apiName,",
        "        property,",
        "        operator,",
        "        },",
        "      );",
        "    }",
        "    return { property, op: 'eq', value: null };",
        "  }",
        "  throw osdkValidationError('INVALID_OSDK_FILTER_OPERATOR', `Unsupported OSDK filter operator ${operator}`, {",
        "    objectType: objectType.apiName,",
        "    property,",
        "    operator,",
        "    supportedOperators: ['$eq', '$in', '$gte', '$lte', '$contains', '$isNull'],",
        "  });",
        "}",
        "",
        "function normalizeOsdkWhere(objectType, where) {",
        "  const filters = [];",
        "  for (const [property, expression] of Object.entries(where)) {",
        "    requireOsdkProperty(objectType, property, 'filter');",
        "    if (!isOsdkRecord(expression)) {",
        "      throw osdkValidationError('INVALID_OSDK_FILTER', 'OSDK property filter must be an object', {",
        "        objectType: objectType.apiName,",
        "        property,",
        "      });",
        "    }",
        "    const operators = Object.entries(expression);",
        "    if (operators.length === 0) {",
        "      throw osdkValidationError('INVALID_OSDK_FILTER', 'OSDK property filter must include an operator', {",
        "        objectType: objectType.apiName,",
        "        property,",
        "      });",
        "    }",
        "    for (const [operator, value] of operators) {",
        "      filters.push(normalizeOsdkPropertyOperator(objectType, property, operator, value));",
        "    }",
        "  }",
        "  if (filters.length === 0) return undefined;",
        "  if (filters.length === 1) return filters[0];",
        "  return { and: filters };",
        "}",
        "",
        "function normalizeOsdkFilterInput(objectType, filter) {",
        "  if (filter === undefined) return undefined;",
        "  if (!isOsdkRecord(filter)) {",
        "    throw osdkValidationError(",
        "      'INVALID_OSDK_FILTER',",
        "      'OSDK filter must be an object',",
        "      { objectType: objectType.apiName },",
        "    );",
        "  }",
        "  if ('property' in filter || 'and' in filter || 'or' in filter) {",
        "    return normalizeLegacyOsdkFilter(objectType, filter);",
        "  }",
        "  return normalizeOsdkWhere(objectType, filter);",
        "}",
        "",
        "function mergeOsdkFilters(left, right) {",
        "  if (left === undefined) return right;",
        "  if (right === undefined) return left;",
        "  return { and: [left, right] };",
        "}",
        "",
        "function normalizeOsdkOrderBy(objectType, orderBy) {",
        "  if (orderBy === undefined) return undefined;",
        "  const rawItems = Array.isArray(orderBy)",
        "    ? orderBy",
        "    : Object.entries(orderBy).map(([property, direction]) => ({ property, direction: String(direction) }));",
        "  if (rawItems.length === 0) return undefined;",
        "  return rawItems.map((item) => {",
        "    if (!isOsdkRecord(item)) {",
        "      throw osdkValidationError(",
        "        'INVALID_OSDK_ORDER',",
        "        'OSDK orderBy item must be an object',",
        "        { objectType: objectType.apiName },",
        "      );",
        "    }",
        "    const property = item.property;",
        "    if (typeof property !== 'string') {",
        "      throw osdkValidationError('INVALID_OSDK_ORDER_PROPERTY', 'OSDK orderBy property must be a string', {",
        "        objectType: objectType.apiName,",
        "      });",
        "    }",
        "    requireOsdkProperty(objectType, property, 'orderBy');",
        "    const direction = item.direction ?? 'asc';",
        "    if (direction !== 'asc' && direction !== 'desc') {",
        "      throw osdkValidationError(",
        "        'INVALID_OSDK_ORDER_DIRECTION',",
        "        'OSDK orderBy direction must be asc or desc',",
        "        {",
        "        objectType: objectType.apiName,",
        "        property,",
        "        direction,",
        "        },",
        "      );",
        "    }",
        "    return { property, direction };",
        "  });",
        "}",
        "",
        "function osdkAggregateSelect(objectType, request) {",
        "  const select = request.$select ?? request.select;",
        "  if (!isOsdkRecord(select)) {",
        "    throw osdkValidationError('INVALID_OSDK_AGGREGATE_SELECT', 'OSDK aggregate requires select', {",
        "      objectType: objectType.apiName,",
        "    });",
        "  }",
        "  const metrics = Object.entries(select).map(([name, value]) => osdkCountMetric(objectType, name, value));",
        "  if (metrics.length === 0) {",
        "    throw osdkValidationError('INVALID_OSDK_AGGREGATE_SELECT', 'OSDK aggregate select must not be empty', {",
        "      objectType: objectType.apiName,",
        "    });",
        "  }",
        "  const orders = new Set(metrics.map((metric) => metric.order));",
        "  if (orders.size !== 1) {",
        "    throw osdkValidationError('INVALID_OSDK_AGGREGATE_SELECT', 'OSDK count metrics must use one ordering', {",
        "      objectType: objectType.apiName,",
        "    });",
        "  }",
        "  return {",
        "    metricNames: metrics.map((metric) => metric.name),",
        "    countOrder: metrics[0].order,",
        "  };",
        "}",
        "",
        "function osdkCountMetric(objectType, name, value) {",
        "  if (name === '$count') return { name: 'count', order: osdkAggregateOrder(objectType, value) };",
        "  if (isOsdkRecord(value) && Object.keys(value).length === 1 && '$count' in value) {",
        "    return { name, order: osdkAggregateOrder(objectType, value.$count) };",
        "  }",
        (
            "  throw osdkValidationError('INVALID_OSDK_AGGREGATE_SELECT', "
            "'Only $count aggregation is currently supported', {"
        ),
        "    objectType: objectType.apiName,",
        "    metric: name,",
        "  });",
        "}",
        "",
        "function osdkAggregateOrder(objectType, value) {",
        "  if (value === 'unordered' || value === 'asc' || value === 'desc') return value;",
        (
            "  throw osdkValidationError('INVALID_OSDK_AGGREGATE_ORDER', "
            "'OSDK aggregate order must be unordered, asc, or desc', {"
        ),
        "    objectType: objectType.apiName,",
        "    order: value,",
        "  });",
        "}",
        "",
        "function osdkAggregateGroupBy(objectType, request) {",
        "  const groupBy = request.$groupBy ?? request.groupBy;",
        "  if (groupBy === undefined) return [];",
        "  if (!isOsdkRecord(groupBy)) {",
        "    throw osdkValidationError('INVALID_OSDK_AGGREGATE_GROUPBY', 'OSDK aggregate groupBy must be an object', {",
        "      objectType: objectType.apiName,",
        "    });",
        "  }",
        "  return Object.entries(groupBy).map(([property, mode]) => {",
        "    requireOsdkProperty(objectType, property, 'aggregate.groupBy');",
        "    if (mode !== 'exact') {",
        (
            "      throw osdkValidationError('INVALID_OSDK_AGGREGATE_GROUPBY', "
            "'Only exact groupBy is currently supported', {"
        ),
        "        objectType: objectType.apiName,",
        "        property,",
        "        mode,",
        "      });",
        "    }",
        "    return property;",
        "  });",
        "}",
        "",
        "function normalizeOsdkAggregateInput(objectType, request) {",
        "  if (!isOsdkRecord(request)) {",
        "    throw osdkValidationError('INVALID_OSDK_AGGREGATE', 'OSDK aggregate request must be an object', {",
        "      objectType: objectType.apiName,",
        "    });",
        "  }",
        "  return {",
        "    ...osdkAggregateSelect(objectType, request),",
        "    groupBy: osdkAggregateGroupBy(objectType, request),",
        "  };",
        "}",
        "",
        "function osdkAggregateOrderBy(objectType, base, groupBy) {",
        "  const baseOrderBy = base.$orderBy !== undefined ? base.$orderBy : base.orderBy;",
        "  const orderBy = normalizeOsdkOrderBy(objectType, baseOrderBy) ?? [];",
        "  const existing = new Set(orderBy.map((item) => item.property));",
        "  for (const property of groupBy) {",
        "    if (!existing.has(property)) orderBy.push({ property, direction: 'asc' });",
        "  }",
        "  return orderBy.length > 0 ? orderBy : undefined;",
        "}",
        "",
        "function osdkQueryPayload(objectType, base, options) {",
        "  const filter = mergeOsdkFilters(",
        "    normalizeOsdkFilterInput(objectType, base.where),",
        "    normalizeOsdkFilterInput(objectType, options.where),",
        "  );",
        "  const requestedOrderBy = options.$orderBy !== undefined ? options.$orderBy : options.orderBy;",
        "  const baseOrderBy = base.$orderBy !== undefined ? base.$orderBy : base.orderBy;",
        "  const orderBy = normalizeOsdkOrderBy(objectType, requestedOrderBy ?? baseOrderBy);",
        "  const pageSize = options.$pageSize !== undefined ? options.$pageSize : options.pageSize;",
        "  const pageToken = options.$pageToken !== undefined ? options.$pageToken : options.pageToken;",
        "  return {",
        "    ...(filter ? { filter } : {}),",
        "    ...(orderBy ? { orderBy } : {}),",
        "    ...(pageSize !== undefined ? { limit: pageSize } : {}),",
        "    ...(pageToken !== undefined ? { cursor: pageToken } : {}),",
        "    ...(options.search !== undefined ? { search: options.search } : {}),",
        "  };",
        "}",
        "",
        "function osdkSubscriptionPayload(objectType, base, options) {",
        "  const query = osdkQueryPayload(objectType, base, { pageSize: options.pageSize });",
        "  return {",
        "    filter: query.filter ?? null,",
        "    orderBy: query.orderBy ?? null,",
        "    properties: options.properties ?? null,",
        "    pageSize: options.pageSize ?? query.limit,",
        "    lastSeenObjectChangeSequence: options.lastSeenObjectChangeSequence ?? null,",
        "    maxEvents: options.maxEvents ?? null,",
        "    pollIntervalSeconds: options.pollIntervalSeconds,",
        "  };",
        "}",
        "",
        "async function consumeObjectSubscription(stream, callbacks, signal) {",
        "  try {",
        "    for await (const frame of stream) {",
        "      if (signal.aborted) return;",
        "      const event = frame.payload;",
        "      if (event.event === 'snapshot') callbacks.onSuccessfulSubscription?.(event);",
        "      else if (event.event === 'object_changed') callbacks.onChange?.(event);",
        "      else if (event.event === 'out_of_date') callbacks.onOutOfDate?.(event);",
        "      else if (event.event === 'error') callbacks.onError?.(event.error);",
        "    }",
        "  } catch (error) {",
        "    if (!signal.aborted) callbacks.onError?.(error);",
        "  }",
        "}",
        "",
        "function startOsdkObjectSubscription(client, objectType, base, callbacks, options = {}) {",
        "  const controller = new AbortController();",
        "  if (options.signal?.aborted) controller.abort();",
        "  options.signal?.addEventListener('abort', () => controller.abort(), { once: true });",
        "  const stream = client.objects.generic.subscribe(",
        "    objectType.apiName,",
        "    osdkSubscriptionPayload(objectType, base, options),",
        "    { ...options, signal: controller.signal },",
        "  );",
        "  const closed = consumeObjectSubscription(stream, callbacks, controller.signal);",
        "  return { unsubscribe: () => controller.abort(), closed };",
        "}",
        "",
        "function osdkPage(result) {",
        "  return {",
        "    data: result.items,",
        "    items: result.items,",
        "    nextPageToken: result.nextCursor,",
        "    nextCursor: result.nextCursor,",
        "  };",
        "}",
        "",
        "function osdkAggregateGroupKey(group) {",
        "  return JSON.stringify(Object.entries(group));",
        "}",
        "",
        "function osdkAggregateItem(plan, states, item) {",
        "  const properties = item.properties ?? {};",
        "  const group = Object.fromEntries(plan.groupBy.map((property) => [property, properties[property] ?? null]));",
        "  const key = osdkAggregateGroupKey(group);",
        "  const state = states.get(key) ?? { group, count: 0 };",
        "  state.count += 1;",
        "  states.set(key, state);",
        "}",
        "",
        "function osdkAggregateResult(plan, states) {",
        "  if (states.size === 0 && plan.groupBy.length === 0) {",
        "    states.set('[]', { group: {}, count: 0 });",
        "  }",
        "  const buckets = Array.from(states.values());",
        "  if (plan.countOrder !== 'unordered') {",
        "    buckets.sort((left, right) =>",
        "      plan.countOrder === 'asc' ? left.count - right.count : right.count - left.count,",
        "    );",
        "  }",
        "  return {",
        "    excludedItems: 0,",
        "    data: buckets.map((state) => ({",
        "      group: state.group,",
        "      metrics: plan.metricNames.map((name) => ({ name, value: state.count })),",
        "    })),",
        "  };",
        "}",
        "",
        "function osdkAggregatePagePayload(objectType, base, plan, pageToken) {",
        "  return osdkQueryPayload(",
        "    objectType,",
        "    { ...base, orderBy: undefined, $orderBy: undefined },",
        "    {",
        "      pageSize: 500,",
        "      pageToken: pageToken ?? undefined,",
        "      orderBy: osdkAggregateOrderBy(objectType, base, plan.groupBy),",
        "    },",
        "  );",
        "}",
        "",
        "async function aggregateOsdkObjectSet(client, objectType, base, request) {",
        "  const plan = normalizeOsdkAggregateInput(objectType, request);",
        "  const states = new Map();",
        "  let pageToken = null;",
        "  for (let pageNumber = 0; pageNumber < 100; pageNumber += 1) {",
        "    const result = await client.objects.generic.query(",
        "      objectType.apiName,",
        "      osdkAggregatePagePayload(objectType, base, plan, pageToken),",
        "    );",
        "    const items = Array.isArray(result.items) ? result.items : [];",
        "    for (const item of items) osdkAggregateItem(plan, states, item);",
        "    pageToken = result.nextCursor ?? null;",
        "    if (!pageToken) return osdkAggregateResult(plan, states);",
        "  }",
        "  throw new FoundryLiteApiError(",
        "    0,",
        '    "CURSOR_LIMIT_EXCEEDED",',
        '    "OSDK aggregate exceeded maxPages",',
        "    { maxPages: 100, objectType: objectType.apiName },",
        "    null,",
        "    false,",
        "  );",
        "}",
        "",
        "function createOsdkLinkSet(client, sourceObjectType, source, entry) {",
        "  return {",
        "    async fetchPage() {",
        "      const links = await client.objects.generic.links(",
        "        sourceObjectType.apiName,",
        "        source.objectId,",
        "        entry.linkType,",
        "      );",
        "      const activeLinks = links.filter((link) => !link.to.targetMissing);",
        "      const items = await Promise.all(activeLinks.map((link) =>",
        "        client.objects.generic.get(entry.targetObjectType.apiName, link.to.objectId),",
        "      ));",
        "      return osdkPage({",
        "        items: items.map((item) => decorateOsdkInstance(client, entry.targetObjectType, item)),",
        "        nextCursor: null,",
        "      });",
        "    },",
        "    async *asyncIter(options = {}) {",
        "      const maxPages = options.maxPages ?? 1;",
        "      if (maxPages < 1) return;",
        "      const page = await this.fetchPage(options);",
        "      yield* page.data;",
        "    },",
        "  };",
        "}",
        "",
        "function createOsdkBoundAction(client, actionType, source) {",
        "  return {",
        "    validateAction(params, options = {}) {",
        "      return createOsdkActionInvoker(client, actionType).validateAction({",
        "        objectId: source.objectId,",
        "        expectedObjectVersion: options.expectedObjectVersion ?? source.objectVersion,",
        "        params,",
        "      });",
        "    },",
        "    applyAction(params, options = {}) {",
        "      return createOsdkActionInvoker(client, actionType).applyAction({",
        "        objectId: source.objectId,",
        "        expectedObjectVersion: options.expectedObjectVersion ?? source.objectVersion,",
        "        params,",
        "        idempotencyKey: options.idempotencyKey,",
        "      }, { onCacheRefresh: options.onCacheRefresh });",
        "    },",
        "  };",
        "}",
        "",
        "function decorateOsdkInstance(client, objectType, item) {",
        "  if (!('$link' in item)) {",
        "    const links = {};",
        "    for (const entry of osdkLinkEntries(objectType)) {",
        "      links[entry.alias] = createOsdkLinkSet(client, objectType, item, entry);",
        "    }",
        "    Object.defineProperty(item, '$link', { value: links, enumerable: false });",
        "  }",
        "  if (!('$actions' in item)) {",
        "    const actions = {};",
        "    for (const entry of osdkActionEntries(objectType)) {",
        "      actions[entry.alias] = createOsdkBoundAction(client, entry.actionType, item);",
        "    }",
        "    Object.defineProperty(item, '$actions', { value: actions, enumerable: false });",
        "  }",
        "  return item;",
        "}",
        "",
        "function createOsdkObjectSet(client, objectType, base = {}) {",
        "  return {",
        "    fetchOne(primaryKey, options) {",
        "      return client.objects.generic",
        "        .get(objectType.apiName, primaryKey, options)",
        "        .then((item) => decorateOsdkInstance(client, objectType, item));",
        "    },",
        "    async fetchPage(options = {}) {",
        "      const result = await client.objects.generic.query(",
        "        objectType.apiName,",
        "        osdkQueryPayload(objectType, base, options),",
        "      );",
        "      return osdkPage({",
        "        items: (Array.isArray(result.items) ? result.items : [])",
        "          .map((item) => decorateOsdkInstance(client, objectType, item)),",
        "        nextCursor: result.nextCursor ?? null,",
        "      });",
        "    },",
        "    async *asyncIter(options = {}) {",
        "      let pageToken = options.$pageToken !== undefined ? options.$pageToken : options.pageToken ?? null;",
        "      const maxPages = options.maxPages ?? 100;",
        "      for (let pageNumber = 0; pageNumber < maxPages; pageNumber += 1) {",
        "        const page = await this.fetchPage({ ...options, pageToken, $pageToken: pageToken });",
        "        yield* page.data;",
        "        pageToken = page.nextPageToken;",
        "        if (!pageToken) return;",
        "      }",
        "      throw new FoundryLiteApiError(",
        "        0,",
        '        "CURSOR_LIMIT_EXCEEDED",',
        '        "OSDK object iteration exceeded maxPages",',
        "        { maxPages },",
        "        null,",
        "        false,",
        "      );",
        "    },",
        "    where(filter) {",
        "      return createOsdkObjectSet(client, objectType, {",
        "        ...base,",
        "        where: mergeOsdkFilters(",
        "          normalizeOsdkFilterInput(objectType, base.where),",
        "          normalizeOsdkFilterInput(objectType, filter),",
        "        ),",
        "      });",
        "    },",
        "    orderBy(orderBy) {",
        "      return createOsdkObjectSet(client, objectType, {",
        "        ...base,",
        "        orderBy: normalizeOsdkOrderBy(objectType, orderBy),",
        "      });",
        "    },",
        "    aggregate(request) {",
        "      return aggregateOsdkObjectSet(client, objectType, base, request);",
        "    },",
        "    links(primaryKey, linkType) {",
        "      return client.objects.generic.links(objectType.apiName, primaryKey, linkType);",
        "    },",
        "    subscribe(callbacks, options = {}) {",
        "      return startOsdkObjectSubscription(client, objectType, base, callbacks, options);",
        "    },",
        "  };",
        "}",
        "",
        "function createOsdkActionInvoker(client, actionType) {",
        "  return {",
        "    validateAction(payload) {",
        "      const actionClient = client.actions[actionType.apiName];",
        "      if (!actionClient) {",
        "        throw new FoundryLiteApiError(",
        "          0,",
        '          "UNKNOWN_OSDK_ACTION",',
        "          `Unknown OSDK action ${actionType.apiName}`,",
        "          { actionApiName: actionType.apiName },",
        "          null,",
        "          false,",
        "        );",
        "      }",
        "      return actionClient.validate(payload);",
        "    },",
        "    applyAction(payload, options = {}) {",
        "      const idempotency = payload.idempotencyKey ?? options.idempotencyKey;",
        "      const actionClient = client.actions[actionType.apiName];",
        "      if (!actionClient) {",
        "        throw new FoundryLiteApiError(",
        "          0,",
        '          "UNKNOWN_OSDK_ACTION",',
        "          `Unknown OSDK action ${actionType.apiName}`,",
        "          { actionApiName: actionType.apiName },",
        "          null,",
        "          false,",
        "        );",
        "      }",
        "      return actionClient.apply({",
        "        ...payload,",
        "        idempotencyKey: requireIdempotencyKey(",
        "          idempotency,",
        "          `osdk.actions.${actionType.apiName}.applyAction`,",
        "        ),",
        "      }).then((result) => {",
        "        if (result.cacheRefresh && options.onCacheRefresh) options.onCacheRefresh(result.cacheRefresh);",
        "        return result;",
        "      });",
        "    },",
        "  };",
        "}",
        "",
        "function createOsdkMediaClient(client) {",
        "  return {",
        "    createSet: (payload) => client.media.sets.create(payload),",
        "    fetchSet: (mediaSetId) => client.media.sets.get(mediaSetId),",
        "    async uploadAndCommit(mediaSetId, payload, options) {",
        "      const transaction = await client.media.transactions.open(",
        "        mediaSetId,",
        "        { mode: options.mode ?? 'APPEND' },",
        "        { idempotencyKey: requireIdempotencyKey(options.idempotencyKey, 'osdk.media.uploadAndCommit') },",
        "      );",
        "      const upload = await client.media.transactions.upload(",
        "        mediaSetId,",
        "        transaction.mediaTransactionId,",
        "        payload,",
        "      );",
        "      const commit = await client.media.transactions.commit(transaction.mediaTransactionId);",
        "      return { transaction, upload, commit };",
        "    },",
        "    process: (mediaItemVersionId, payload) => client.media.versions.process(mediaItemVersionId, payload),",
        "    index: (mediaDerivativeId, payload) => client.media.derivatives.index(mediaDerivativeId, payload),",
        "    search: (payload) => client.media.content.search(payload),",
        "    bindReference: (payload, options) => client.media.references.bind(payload, options),",
        "    fetchReference: (payload) => client.media.references.resolve(payload),",
        "  };",
        "}",
        "",
        "export function createFoundryLiteOsdkClient(client) {",
        "  const osdk = (resource) => {",
        "    if (resource.kind === 'object') return createOsdkObjectSet(client, resource);",
        "    if (resource.kind === 'action') return createOsdkActionInvoker(client, resource);",
        "    throw new FoundryLiteApiError(",
        "      0,",
        '      "INVALID_OSDK_RESOURCE",',
        "      'OSDK resource must be an object type or action type',",
        "      { resource },",
        "      null,",
        "      false,",
        "    );",
        "  };",
        "  return Object.assign(osdk, {",
        "    objects: $Objects,",
        "    actions: $Actions,",
        "    media: createOsdkMediaClient(client),",
        "  });",
        "}",
    ]
