// Generated by scripts/generate_consumer_osdk.py. Do not edit by hand.
import type {
  ActionApplyResponse,
  FoundryLiteObject,
  OsdkActionType,
  OsdkFunctionType,
  OsdkObjectType,
} from "@foundry-lite/sdk";

export type ReservationPolicyQuote = {
  readonly decision: string;
  readonly isBookable: boolean;
  readonly reasonCodes: string[];
  readonly depositAmountKrw: number;
  readonly cancellationDeadlineAt: string;
  readonly lateArrivalGraceMinutes: number;
  readonly quoteExpiresAt: string;
  readonly inventoryHoldStatus: string;
  readonly holdDurationMinutes: number;
  readonly serviceEndsAt: string;
  readonly turnTimeMinutes: number;
  readonly policyVersion: string;
  readonly policyMessage: string;
};

export type RestaurantProperties = {
  readonly id: string;
  readonly restaurantId: string;
  readonly name: string;
  readonly location: string;
  readonly status: string;
  readonly timeZone: string;
  readonly serviceStartLocal: string;
  readonly lastSeatingLocal: string;
  readonly slotIntervalMinutes: number;
  readonly bookingWindowDays: number;
  readonly minAdvanceMinutes: number;
  readonly closedWeekdaysCsv: string;
  readonly maxOnlinePartySize: number;
  readonly largePartyThreshold: number;
  readonly depositPerPersonKrw: number;
  readonly cancellationCutoffHours: number;
  readonly lateArrivalGraceMinutes: number;
  readonly quoteValidityMinutes: number;
  readonly depositHoldMinutes: number;
  readonly autoConfirmPartySizeMax: number;
  readonly policyVersion: string;
  readonly policyMessage: string;
};

export type Restaurant = FoundryLiteObject<"Restaurant", RestaurantProperties>;
export const Restaurant = {
  kind: "object",
  apiName: "Restaurant",
  primaryKey: "id",
  titleProperty: "name",
  properties: ["id", "restaurantId", "name", "location", "status", "timeZone", "serviceStartLocal", "lastSeatingLocal", "slotIntervalMinutes", "bookingWindowDays", "minAdvanceMinutes", "closedWeekdaysCsv", "maxOnlinePartySize", "largePartyThreshold", "depositPerPersonKrw", "cancellationCutoffHours", "lateArrivalGraceMinutes", "quoteValidityMinutes", "depositHoldMinutes", "autoConfirmPartySizeMax", "policyVersion", "policyMessage"],
  propertyDatasources: {},
} as const as OsdkObjectType<Restaurant>;

export type DiningTableProperties = {
  readonly id: string;
  readonly restaurantId: string;
  readonly tableId: string;
  readonly label: string;
  readonly capacity: number;
  readonly status: string;
  readonly area: string;
  readonly minPartySize: number;
  readonly turnTimeMinutes: number;
  readonly isAccessible: boolean;
  readonly isHighChairCompatible: boolean;
  readonly isCombinable: boolean;
  readonly tableType: string;
  readonly reservationLedgerJson: string;
  readonly inventoryUpdatedAt?: string;
  readonly lastReservationId?: string;
};

export type DiningTable = FoundryLiteObject<"DiningTable", DiningTableProperties>;
export const DiningTable = {
  kind: "object",
  apiName: "DiningTable",
  primaryKey: "id",
  titleProperty: "label",
  properties: ["id", "restaurantId", "tableId", "label", "capacity", "status", "area", "minPartySize", "turnTimeMinutes", "isAccessible", "isHighChairCompatible", "isCombinable", "tableType", "reservationLedgerJson", "inventoryUpdatedAt", "lastReservationId"],
  propertyDatasources: {},
} as const as OsdkObjectType<DiningTable>;

export type ReservationProperties = {
  readonly id: string;
  readonly reservationId: string;
  readonly restaurantId: string;
  readonly tableId: string;
  readonly guestName: string;
  readonly guestPhone: string;
  readonly guestEmail: string;
  readonly partySize: number;
  readonly reservationAt: string;
  readonly status: string;
  readonly requestedAt: string;
  readonly createdAt: string;
  readonly seatingPreference: string;
  readonly specialRequest: string;
  readonly policyVersion: string;
  readonly policyDecision: string;
  readonly quotedDepositKrw: number;
  readonly cancellationDeadlineAt: string;
  readonly lateArrivalGraceMinutes: number;
  readonly quoteExpiresAt: string;
  readonly inventoryHoldStatus: string;
  readonly turnTimeMinutes: number;
  readonly customerAcceptedPolicy: boolean;
  readonly sourceChannel: string;
  readonly holdExpiresAt: string;
  readonly inventoryVersion: number;
  readonly paymentStatus: string;
  readonly paymentProvider: string;
  readonly paymentAttemptId: string;
  readonly paymentReference: string;
  readonly paymentAuthorizedAt: string;
  readonly paidDepositKrw: number;
  readonly refundStatus: string;
  readonly refundReference: string;
  readonly refundedAmountKrw: number;
  readonly refundedAt: string;
  readonly cancellationId: string;
  readonly cancellationReason: string;
  readonly cancelledAt: string;
};

export type Reservation = FoundryLiteObject<"Reservation", ReservationProperties>;
export const Reservation = {
  kind: "object",
  apiName: "Reservation",
  primaryKey: "id",
  titleProperty: "reservationId",
  properties: ["id", "reservationId", "restaurantId", "tableId", "guestName", "guestPhone", "guestEmail", "partySize", "reservationAt", "status", "requestedAt", "createdAt", "seatingPreference", "specialRequest", "policyVersion", "policyDecision", "quotedDepositKrw", "cancellationDeadlineAt", "lateArrivalGraceMinutes", "quoteExpiresAt", "inventoryHoldStatus", "turnTimeMinutes", "customerAcceptedPolicy", "sourceChannel", "holdExpiresAt", "inventoryVersion", "paymentStatus", "paymentProvider", "paymentAttemptId", "paymentReference", "paymentAuthorizedAt", "paidDepositKrw", "refundStatus", "refundReference", "refundedAmountKrw", "refundedAt", "cancellationId", "cancellationReason", "cancelledAt"],
  propertyDatasources: {},
} as const as OsdkObjectType<Reservation>;

export type QuoteAtomicReservationPolicyInputs = {
  readonly restaurant: string;
  readonly table: string;
  readonly desiredAt: string;
  readonly requestedAt: string;
  readonly partySize: number;
  readonly guestPhone: string;
  readonly seatingPreference: string;
};

export const QuoteAtomicReservationPolicy = {
  kind: "function",
  apiName: "QuoteAtomicReservationPolicy",
  inputs: [{"apiName":"restaurant","type":"string","required":true}, {"apiName":"table","type":"string","required":true}, {"apiName":"desiredAt","type":"string","required":true}, {"apiName":"requestedAt","type":"string","required":true}, {"apiName":"partySize","type":"number","required":true}, {"apiName":"guestPhone","type":"string","required":true}, {"apiName":"seatingPreference","type":"string","required":true}],
  output: "ReservationPolicyQuote",
} as const as OsdkFunctionType<QuoteAtomicReservationPolicyInputs, ReservationPolicyQuote>;

export type ReserveTableWithAtomicInventoryParams = {
  readonly restaurant: string;
  readonly table: string;
  readonly reservationId: string;
  readonly guestName: string;
  readonly guestPhone: string;
  readonly guestEmail: string;
  readonly partySize: number;
  readonly desiredAt: string;
  readonly requestedAt: string;
  readonly seatingPreference: string;
  readonly specialRequest: string;
  readonly customerAcceptedPolicy: boolean;
};

export type ReserveTableWithAtomicInventoryRequest = {
  readonly objectType?: "Restaurant";
  readonly objectId: string;
  readonly expectedObjectVersion: number;
  readonly params: ReserveTableWithAtomicInventoryParams;
  readonly idempotencyKey: string;
};
export const ReserveTableWithAtomicInventory = {
  kind: "action",
  apiName: "ReserveTableWithAtomicInventory",
  targetObjectType: "Restaurant",
  targetKind: "object",
} as const as OsdkActionType<ReserveTableWithAtomicInventoryRequest, ActionApplyResponse>;

export type PayReservationDepositParams = {
  readonly reservation: string;
  readonly table: string;
  readonly paymentAttemptId: string;
  readonly paymentMethodRef: string;
  readonly requestedAt: string;
};

export type PayReservationDepositRequest = {
  readonly objectType?: "Reservation";
  readonly objectId: string;
  readonly expectedObjectVersion: number;
  readonly params: PayReservationDepositParams;
  readonly idempotencyKey: string;
};
export const PayReservationDeposit = {
  kind: "action",
  apiName: "PayReservationDeposit",
  targetObjectType: "Reservation",
  targetKind: "object",
} as const as OsdkActionType<PayReservationDepositRequest, ActionApplyResponse>;

export type CancelCustomerReservationParams = {
  readonly reservation: string;
  readonly table: string;
  readonly cancellationId: string;
  readonly cancellationReason: string;
  readonly requestedAt: string;
};

export type CancelCustomerReservationRequest = {
  readonly objectType?: "Reservation";
  readonly objectId: string;
  readonly expectedObjectVersion: number;
  readonly params: CancelCustomerReservationParams;
  readonly idempotencyKey: string;
};
export const CancelCustomerReservation = {
  kind: "action",
  apiName: "CancelCustomerReservation",
  targetObjectType: "Reservation",
  targetKind: "object",
} as const as OsdkActionType<CancelCustomerReservationRequest, ActionApplyResponse>;

export const $Objects = { Restaurant, DiningTable, Reservation } as const;
export const $Functions = { QuoteAtomicReservationPolicy } as const;
export const $Actions = { ReserveTableWithAtomicInventory, PayReservationDeposit, CancelCustomerReservation } as const;
export const CONSUMER_OSDK_MANIFEST = {"schemaVersion":"foundry-lite-consumer-osdk-manifest/v1","applicationId":"restaurant-reservation-customer","packageName":"@foundry-lite/restaurant-reservation-osdk","profile":"consumer_osdk_strict","ontologyFingerprint":"sha256:7ba09600170bd95d3146f8042b17eec19e4b6222be43285be024bb270fc658b9","objectApiNames":["Restaurant","DiningTable","Reservation"],"functionApiNames":["QuoteAtomicReservationPolicy"],"actionApiNames":["ReserveTableWithAtomicInventory","PayReservationDeposit","CancelCustomerReservation"]} as const;
