"""Generate application-scoped, high-level TypeScript OSDK packages."""

from __future__ import annotations

import argparse
import hashlib
import json
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import cast

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INVENTORY = ROOT / "config/consumer-osdk-apps.json"
JsonObject = dict[str, object]


def _json_object(path: Path) -> JsonObject:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return cast(JsonObject, value)


def _objects(value: object, field: str) -> list[JsonObject]:
    if not isinstance(value, list) or not all(isinstance(item, dict) for item in value):
        raise ValueError(f"{field} must be an array of objects")
    return cast(list[JsonObject], value)


def _string(row: Mapping[str, object], field: str) -> str:
    value = row.get(field)
    if not isinstance(value, str) or not value:
        raise ValueError(f"{field} must be a non-empty string")
    return value


def _canonical_hash(value: Mapping[str, object]) -> str:
    encoded = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    return f"sha256:{hashlib.sha256(encoded).hexdigest()}"


def _field_lines(name: str, fields: Sequence[JsonObject]) -> list[str]:
    lines = [f"export type {name} = {{"]
    for field in fields:
        optional = "?" if field.get("optional") is True else ""
        lines.append(f"  readonly {_string(field, 'name')}{optional}: {_string(field, 'type')};")
    lines.extend(["};", ""])
    return lines


def _object_lines(row: JsonObject) -> list[str]:
    api_name = _string(row, "apiName")
    properties = _objects(row.get("properties"), f"{api_name}.properties")
    property_names = ", ".join(json.dumps(_string(item, "name")) for item in properties)
    lines = _field_lines(f"{api_name}Properties", properties)
    lines.extend(
        [
            f'export type {api_name} = FoundryLiteObject<"{api_name}", {api_name}Properties>;',
            f"export const {api_name} = {{",
            '  kind: "object",',
            f'  apiName: "{api_name}",',
            f"  primaryKey: {json.dumps(_string(row, 'primaryKey'))},",
            f"  titleProperty: {json.dumps(row.get('titleProperty'))},",
            f"  properties: [{property_names}],",
            "  propertyDatasources: {},",
            f"}} as const as OsdkObjectType<{api_name}>;",
            "",
        ]
    )
    return lines


def _function_lines(row: JsonObject) -> list[str]:
    api_name = _string(row, "apiName")
    inputs = _objects(row.get("inputs"), f"{api_name}.inputs")
    lines = _field_lines(f"{api_name}Inputs", inputs)
    input_metadata = ", ".join(
        json.dumps(
            {
                "apiName": _string(item, "name"),
                "type": _string(item, "type"),
                "required": item.get("optional") is not True,
            },
            separators=(",", ":"),
        )
        for item in inputs
    )
    output_type = _string(row, "outputType")
    lines.extend(
        [
            f"export const {api_name} = {{",
            '  kind: "function",',
            f'  apiName: "{api_name}",',
            f"  inputs: [{input_metadata}],",
            f"  output: {json.dumps(output_type)},",
            (f"}} as const as OsdkFunctionType<{api_name}Inputs, {output_type}>;"),
            "",
        ]
    )
    return lines


def _action_lines(row: JsonObject) -> list[str]:
    api_name = _string(row, "apiName")
    target = _string(row, "targetObjectType")
    parameters = _objects(row.get("parameters"), f"{api_name}.parameters")
    lines = _field_lines(f"{api_name}Params", parameters)
    lines.extend(
        [
            f"export type {api_name}Request = {{",
            f'  readonly objectType?: "{target}";',
            "  readonly objectId: string;",
            "  readonly expectedObjectVersion: number;",
            f"  readonly params: {api_name}Params;",
            "  readonly idempotencyKey: string;",
            "};",
            f"export const {api_name} = {{",
            '  kind: "action",',
            f'  apiName: "{api_name}",',
            f'  targetObjectType: "{target}",',
            '  targetKind: "object",',
            f"}} as const as OsdkActionType<{api_name}Request, ActionApplyResponse>;",
            "",
        ]
    )
    return lines


def render_contract(contract: JsonObject) -> str:
    objects = _objects(contract.get("objects"), "objects")
    functions = _objects(contract.get("functions"), "functions")
    actions = _objects(contract.get("actions"), "actions")
    domain_types = _objects(contract.get("domainTypes"), "domainTypes")
    lines = [
        "// Generated by scripts/generate_consumer_osdk.py. Do not edit by hand.",
        "import type {",
        "  ActionApplyResponse,",
        "  FoundryLiteObject,",
        "  OsdkActionType,",
        "  OsdkFunctionType,",
        "  OsdkObjectType,",
        '} from "@foundry-lite/sdk";',
        "",
    ]
    for row in domain_types:
        lines.extend(_field_lines(_string(row, "name"), _objects(row.get("fields"), "domainTypes.fields")))
    for row in objects:
        lines.extend(_object_lines(row))
    for row in functions:
        lines.extend(_function_lines(row))
    for row in actions:
        lines.extend(_action_lines(row))
    object_names = [_string(row, "apiName") for row in objects]
    function_names = [_string(row, "apiName") for row in functions]
    action_names = [_string(row, "apiName") for row in actions]
    manifest = {
        "schemaVersion": "foundry-lite-consumer-osdk-manifest/v1",
        "applicationId": _string(contract, "applicationId"),
        "packageName": _string(contract, "packageName"),
        "profile": "consumer_osdk_strict",
        "ontologyFingerprint": _canonical_hash(contract),
        "objectApiNames": object_names,
        "functionApiNames": function_names,
        "actionApiNames": action_names,
    }
    lines.extend(
        [
            f"export const $Objects = {{ {', '.join(object_names)} }} as const;",
            f"export const $Functions = {{ {', '.join(function_names)} }} as const;",
            f"export const $Actions = {{ {', '.join(action_names)} }} as const;",
            "export const CONSUMER_OSDK_MANIFEST = "
            + json.dumps(manifest, ensure_ascii=False, separators=(",", ":"))
            + " as const;",
            "",
        ]
    )
    return "\n".join(lines)


def generate(inventory_path: Path, *, is_check: bool) -> list[Path]:
    inventory = _json_object(inventory_path)
    changed: list[Path] = []
    for app in _objects(inventory.get("applications"), "applications"):
        contract_path = ROOT / _string(app, "contractPath")
        output_path = ROOT / _string(app, "generatedPath")
        rendered = render_contract(_json_object(contract_path))
        if output_path.exists() and output_path.read_text(encoding="utf-8") == rendered:
            continue
        changed.append(output_path)
        if not is_check:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(rendered, encoding="utf-8")
    return changed


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--inventory", type=Path, default=DEFAULT_INVENTORY)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed = generate(args.inventory, is_check=args.check)
    if args.check and changed:
        names = ", ".join(str(path.relative_to(ROOT)) for path in changed)
        raise SystemExit(f"consumer OSDK generated files are stale: {names}")
    for path in changed:
        print(f"Wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
