"""Generate the Sprint 35 TypeScript SDK from the active demo ontology."""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping, Sequence
from dataclasses import asdict, dataclass
from hashlib import sha256
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ONTOLOGY = ROOT / "examples" / "supply-chain-demo" / "ontology" / "order-customer.yaml"
DEFAULT_TS_OUTPUT = ROOT / "packages" / "sdk-ts" / "src" / "generated.ts"
DEFAULT_WEB_OUTPUT = ROOT / "apps" / "web" / "generated-sdk.js"
SCALAR_TYPES = {
    "boolean": "boolean",
    "float": "number",
    "integer": "number",
    "string": "string",
}


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


@dataclass(frozen=True)
class PropertyDef:
    api_name: str
    ts_type: str
    is_required: bool
    is_sensitive: bool


@dataclass(frozen=True)
class ObjectDef:
    api_name: str
    properties: tuple[PropertyDef, ...]


@dataclass(frozen=True)
class ParameterDef:
    api_name: str
    ts_type: str
    is_required: bool


@dataclass(frozen=True)
class ActionDef:
    api_name: str
    target: str
    parameters: tuple[ParameterDef, ...]


@dataclass(frozen=True)
class OntologyDef:
    objects: tuple[ObjectDef, ...]
    actions: tuple[ActionDef, ...]


@dataclass(frozen=True)
class ObjectClientSurface:
    api_name: str
    response_type: str
    methods: tuple[str, ...]


@dataclass(frozen=True)
class ActionClientSurface:
    api_name: str
    target: str
    payload_type: str
    methods: tuple[str, ...]


@dataclass(frozen=True)
class SdkClientSurface:
    objects: tuple[ObjectClientSurface, ...]
    actions: tuple[ActionClientSurface, ...]
    helpers: tuple[str, ...]


def load_ontology(path: Path) -> OntologyDef:
    document = _mapping(yaml.safe_load(path.read_text(encoding="utf-8")), "ontology")
    return OntologyDef(
        objects=tuple(_object_def(row) for row in _sequence(document.get("objectTypes"), "objectTypes")),
        actions=tuple(_action_def(row) for row in _sequence(document.get("actionTypes"), "actionTypes")),
    )


def client_surface(ontology: OntologyDef) -> SdkClientSurface:
    return SdkClientSurface(
        objects=tuple(ObjectClientSurface(item.api_name, item.api_name, ("get", "query")) for item in ontology.objects),
        actions=tuple(
            ActionClientSurface(item.api_name, item.target, f"{item.api_name}ApplyRequest", ("apply",))
            for item in ontology.actions
        ),
        helpers=("createFoundryLiteClient", "expectedObjectVersion", "idempotencyKey"),
    )


def render_client_surface_json(surface: SdkClientSurface) -> str:
    payload: dict[str, object] = {
        "actions": {item.api_name: list(item.methods) for item in surface.actions},
        "helpers": list(surface.helpers),
        "objects": {item.api_name: list(item.methods) for item in surface.objects},
    }
    return json.dumps(payload, sort_keys=True, separators=(",", ":"))


def render_typescript(ontology: OntologyDef) -> str:
    surface = client_surface(ontology)
    lines = [
        "/* generated by scripts/generate_sdk_ts.py; do not edit by hand */",
        f'export const ONTOLOGY_CONTRACT_FINGERPRINT = "{contract_fingerprint(ontology)}";',
        f"export const SDK_CLIENT_SURFACE = {render_client_surface_json(surface)};",
        "",
        "export type FoundryLiteClientOptions = {",
        "  baseUrl: string;",
        "  headers?: Record<string, string>;",
        "  token?: string;",
        "  fetchImpl?: typeof fetch;",
        "};",
        "",
        "export type FoundryLiteObject<ApiName extends string, Properties> = {",
        "  objectType: ApiName;",
        "  objectId: string;",
        "  objectVersion: number;",
        "  properties: Properties;",
        "  sourceDatasetVersionId?: string | null;",
        "  explain?: { sourceRunChain?: Array<Record<string, unknown>> };",
        "};",
        "",
        "export type ObjectFilter = Record<string, unknown>;",
        (
            "export type ObjectQueryRequest = { filter?: ObjectFilter; "
            "orderBy?: Array<Record<string, string>>; limit?: number; cursor?: string | null; search?: string | null };"
        ),
        "export type ObjectQueryResult<Item> = { items: Item[]; nextCursor: string | null };",
        "export type ActionApplyResponse = { status: string; actionRunId?: string; object?: Record<string, unknown> };",
        "",
    ]
    for object_def in ontology.objects:
        lines.extend(_object_type_lines(object_def))
    for action_def in ontology.actions:
        lines.extend(_action_type_lines(action_def))
    lines.extend(_client_type_lines(surface))
    lines.extend(_client_runtime_lines(surface))
    return "\n".join(lines) + "\n"


def render_web_javascript(ontology: OntologyDef) -> str:
    surface = client_surface(ontology)
    lines = [
        "// generated by scripts/generate_sdk_ts.py; do not edit by hand",
        f'export const ONTOLOGY_CONTRACT_FINGERPRINT = "{contract_fingerprint(ontology)}";',
        f"export const SDK_CLIENT_SURFACE = {render_client_surface_json(surface)};",
        "",
        "export function idempotencyKey(actionName, objectId) {",
        "  return `${actionName}-${objectId}-${Date.now()}`;",
        "}",
        "",
        "export function expectedObjectVersion(object) {",
        "  return object.objectVersion;",
        "}",
        "",
        "export function createFoundryLiteClient(options) {",
        "  async function request(path, init = {}) {",
        "    const fetcher = options.fetchImpl ?? fetch;",
        "    const response = await fetcher(`${options.baseUrl}${path}`, {",
        "      ...init,",
        "      headers: {",
        "        ...(options.token ? { Authorization: `Bearer ${options.token}` } : {}),",
        "        ...(options.headers ?? {}),",
        "        ...(init.headers ?? {}),",
        "      },",
        "    });",
        "    const body = await response.json().catch(() => ({}));",
        "    if (!response.ok) {",
        "      throw body;",
        "    }",
        "    return body;",
        "  }",
        "",
        "  return {",
        "    objects: {",
    ]
    lines.extend(_web_object_client_lines(surface.objects))
    lines.extend(["    },", "    actions: {"])
    lines.extend(_web_action_client_lines(surface.actions))
    lines.extend(["    },", "  };", "}", ""])
    return "\n".join(lines)


def contract_fingerprint(ontology: OntologyDef) -> str:
    payload = json.dumps(asdict(ontology), sort_keys=True, separators=(",", ":"))
    return sha256(payload.encode("utf-8")).hexdigest()[:16]


def write_or_check_outputs(
    *,
    ontology_path: Path,
    ts_output: Path,
    web_output: Path,
    should_check: bool,
) -> int:
    ontology = load_ontology(ontology_path)
    outputs = {
        ts_output: render_typescript(ontology),
        web_output: render_web_javascript(ontology),
    }
    if should_check:
        stale = [
            path
            for path, content in outputs.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print("SDK generation check failed: generated outputs are stale or ontology apiNames changed.")
            for path in stale:
                print(f"- {_display_path(path)}")
            return 1
        print("SDK generation check passed: generated outputs match the active ontology.")
        return 0
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {_display_path(path)}")
    return 0


def _object_type_lines(object_def: ObjectDef) -> list[str]:
    properties_name = f"{object_def.api_name}Properties"
    lines = [f"export type {properties_name} = {{"]
    for prop in object_def.properties:
        suffix = "" if prop.is_required else "?"
        lines.append(f"  {prop.api_name}{suffix}: {prop.ts_type};")
    lines.extend(
        [
            "};",
            f'export type {object_def.api_name} = FoundryLiteObject<"{object_def.api_name}", {properties_name}>;',
            "",
        ]
    )
    return lines


def _action_type_lines(action_def: ActionDef) -> list[str]:
    params_name = f"{action_def.api_name}Params"
    payload_name = f"{action_def.api_name}ApplyRequest"
    lines = [f"export type {params_name} = {{"]
    for param in action_def.parameters:
        suffix = "" if param.is_required else "?"
        lines.append(f"  {param.api_name}{suffix}: {param.ts_type};")
    lines.extend(
        [
            "};",
            f"export type {payload_name} = {{",
            "  objectId: string;",
            "  expectedObjectVersion: number;",
            f"  params: {params_name};",
            "  idempotencyKey?: string;",
            "};",
            "",
        ]
    )
    return lines


def _client_type_lines(surface: SdkClientSurface) -> list[str]:
    lines = ["export type FoundryLiteGeneratedClient = {", "  objects: {"]
    for object_def in surface.objects:
        lines.extend(
            [
                f"    {object_def.api_name}: {{",
                f"      get(id: string, options?: {{ explain?: boolean }}): Promise<{object_def.response_type}>;",
                f"      query(payload?: ObjectQueryRequest): Promise<ObjectQueryResult<{object_def.response_type}>>;",
                "    };",
            ]
        )
    lines.extend(["  };", "  actions: {"])
    for action_def in surface.actions:
        lines.extend(
            [
                f"    {action_def.api_name}: {{",
                f"      apply(payload: {action_def.payload_type}): Promise<ActionApplyResponse>;",
                "    };",
            ]
        )
    lines.extend(["  };", "};", ""])
    return lines


def _client_runtime_lines(surface: SdkClientSurface) -> list[str]:
    lines = [
        "export function idempotencyKey(actionName: string, objectId: string): string {",
        "  return `${actionName}-${objectId}-${Date.now()}`;",
        "}",
        "",
        "export function expectedObjectVersion(object: { objectVersion: number }): number {",
        "  return object.objectVersion;",
        "}",
        "",
        (
            "export function createFoundryLiteClient"
            "(clientOptions: FoundryLiteClientOptions): FoundryLiteGeneratedClient {"
        ),
        "  async function request<T>(path: string, init?: RequestInit): Promise<T> {",
        "    const fetcher = clientOptions.fetchImpl ?? fetch;",
        "    const response = await fetcher(`${clientOptions.baseUrl}${path}`, {",
        "      ...init,",
        "      headers: {",
        "        ...(clientOptions.token ? { Authorization: `Bearer ${clientOptions.token}` } : {}),",
        "        ...(clientOptions.headers ?? {}),",
        "        ...(init?.headers ?? {}),",
        "      },",
        "    });",
        "    const body = await response.json().catch(() => ({}));",
        "    if (!response.ok) {",
        "      throw body;",
        "    }",
        "    return body as T;",
        "  }",
        "",
        "  return {",
        "    objects: {",
    ]
    lines.extend(_ts_object_client_lines(surface.objects))
    lines.extend(["    },", "    actions: {"])
    lines.extend(_ts_action_client_lines(surface.actions))
    lines.extend(["    },", "  };", "}", ""])
    return lines


def _ts_object_client_lines(objects: Sequence[ObjectClientSurface]) -> list[str]:
    lines: list[str] = []
    for object_def in objects:
        path_name = json.dumps(object_def.api_name)
        lines.extend(
            [
                f"      {object_def.api_name}: {{",
                "        get: (id: string, options?: { explain?: boolean }) => {",
                "          const suffix = options?.explain ? '?explain=true' : '';",
                (
                    f"          return request<{object_def.response_type}>(`/api/objects/{object_def.api_name}/"
                    "${encodeURIComponent(id)}${suffix}`);"
                ),
                "        },",
                "        query: (payload: ObjectQueryRequest = {}) =>",
                (
                    f"          request<ObjectQueryResult<{object_def.response_type}>>"
                    f"(`/api/objects/{object_def.api_name}/query`, {{"
                ),
                '            method: "POST",',
                f"            headers: {{ 'Content-Type': 'application/json', 'X-Foundry-Lite-Object': {path_name} }},",
                "            body: JSON.stringify(payload),",
                "          }),",
                "      },",
            ]
        )
    return lines


def _ts_action_client_lines(actions: Sequence[ActionClientSurface]) -> list[str]:
    lines: list[str] = []
    for action_def in actions:
        target = json.dumps(action_def.target)
        action_name = json.dumps(action_def.api_name)
        lines.extend(
            [
                f"      {action_def.api_name}: {{",
                f"        apply: (payload: {action_def.payload_type}) =>",
                f"          request<ActionApplyResponse>(`/api/actions/{action_def.api_name}/apply`, {{",
                '            method: "POST",',
                "            headers: {",
                '              "Content-Type": "application/json",',
                '              "Idempotency-Key": payload.idempotencyKey ?? idempotencyKey(',
                f"                {action_name},",
                "                payload.objectId,",
                "              ),",
                "            },",
                "            body: JSON.stringify({",
                f"              target: {{ objectType: {target}, objectId: payload.objectId }},",
                "              expectedObjectVersion: payload.expectedObjectVersion,",
                "              params: payload.params,",
                "            }),",
                "          }),",
                "      },",
            ]
        )
    return lines


def _web_object_client_lines(objects: Sequence[ObjectClientSurface]) -> list[str]:
    lines: list[str] = []
    for object_def in objects:
        lines.extend(
            [
                f"      {object_def.api_name}: {{",
                "        get: (id, requestOptions = {}) => {",
                "          const suffix = requestOptions.explain ? '?explain=true' : '';",
                (
                    f"          return request(`/api/objects/{object_def.api_name}/"
                    "${encodeURIComponent(id)}${suffix}`);"
                ),
                "        },",
                f"        query: (payload = {{}}) => request(`/api/objects/{object_def.api_name}/query`, {{",
                '          method: "POST",',
                '          headers: { "Content-Type": "application/json" },',
                "          body: JSON.stringify(payload),",
                "        }),",
                "      },",
            ]
        )
    return lines


def _web_action_client_lines(actions: Sequence[ActionClientSurface]) -> list[str]:
    lines: list[str] = []
    for action_def in actions:
        lines.extend(
            [
                f"      {action_def.api_name}: {{",
                f"        apply: (payload) => request(`/api/actions/{action_def.api_name}/apply`, {{",
                '          method: "POST",',
                "          headers: {",
                '            "Content-Type": "application/json",',
                (
                    '            "Idempotency-Key": payload.idempotencyKey ?? '
                    f'idempotencyKey("{action_def.api_name}", payload.objectId),'
                ),
                "          },",
                "          body: JSON.stringify({",
                f'            target: {{ objectType: "{action_def.target}", objectId: payload.objectId }},',
                "            expectedObjectVersion: payload.expectedObjectVersion,",
                "            params: payload.params,",
                "          }),",
                "        }),",
                "      },",
            ]
        )
    return lines


def _object_def(value: object) -> ObjectDef:
    row = _mapping(value, "objectTypes[]")
    properties = tuple(_property_def(item) for item in _sequence(row.get("properties"), "properties"))
    return ObjectDef(api_name=_string(row.get("apiName"), "object apiName"), properties=properties)


def _property_def(value: object) -> PropertyDef:
    row = _mapping(value, "properties[]")
    is_sensitive = isinstance(row.get("classification"), str)
    ts_type = _ts_type(_string(row.get("type"), "property type"), is_sensitive=is_sensitive)
    return PropertyDef(
        api_name=_string(row.get("apiName"), "property apiName"),
        ts_type=ts_type,
        is_required=row.get("nullable") is False,
        is_sensitive=is_sensitive,
    )


def _action_def(value: object) -> ActionDef:
    row = _mapping(value, "actionTypes[]")
    parameters = tuple(_parameter_def(item) for item in _sequence(row.get("parameters"), "parameters"))
    return ActionDef(
        api_name=_string(row.get("apiName"), "action apiName"),
        target=_string(row.get("target"), "action target"),
        parameters=parameters,
    )


def _parameter_def(value: object) -> ParameterDef:
    row = _mapping(value, "parameters[]")
    return ParameterDef(
        api_name=_string(row.get("apiName"), "parameter apiName"),
        ts_type=_ts_type(_string(row.get("type"), "parameter type"), is_sensitive=False),
        is_required=row.get("required") is not False,
    )


def _ts_type(value: str, *, is_sensitive: bool) -> str:
    scalar = SCALAR_TYPES.get(value, "unknown")
    return f"{scalar} | string" if is_sensitive and scalar != "string" else scalar


def _mapping(value: object, field: str) -> Mapping[str, object]:
    if not isinstance(value, dict):
        raise ValueError(f"{field} must be an object")
    return value


def _sequence(value: object, field: str) -> Sequence[object]:
    if value is None:
        return ()
    if not isinstance(value, list):
        raise ValueError(f"{field} must be a list")
    return value


def _string(value: object, field: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{field} must be a non-empty string")
    return value


def _parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Foundry-lite TypeScript SDK from ontology YAML.")
    parser.add_argument("--ontology", type=Path, default=DEFAULT_ONTOLOGY)
    parser.add_argument("--ts-output", type=Path, default=DEFAULT_TS_OUTPUT)
    parser.add_argument("--web-output", type=Path, default=DEFAULT_WEB_OUTPUT)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv or sys.argv[1:])
    return write_or_check_outputs(
        ontology_path=args.ontology,
        ts_output=args.ts_output,
        web_output=args.web_output,
        should_check=args.check,
    )


if __name__ == "__main__":
    sys.exit(main())
