/* generated by scripts/generate_sdk_ts.py; do not edit by hand */
export const ONTOLOGY_CONTRACT_FINGERPRINT = "a622ceca207f76d4";
export const SDK_CLIENT_SURFACE = {"actions":{"ApproveOrder":["apply"]},"helpers":["createFoundryLiteClient","createRequestId","expectedObjectVersion","idempotencyKey","isRetryableFoundryLiteError","normalizeFoundryLiteError","requestContextHeaders"],"objects":{"Customer":["get","query"],"Order":["get","query"]},"operations":{"backupRestore":["preflight","startRestoreMode","restoreModeStatus","approveResume"],"deadLetterRecords":["list","get","retry","bulkRetry","discard"],"icebergMaintenance":["plan"],"observability":["detect"],"reconciliation":["resolve"],"workflows":["startConnectorSync","get"]}};

export type FoundryLiteClientOptions = {
  baseUrl: string;
  headers?: Record<string, string>;
  token?: string;
  fetchImpl?: typeof fetch;
  context?: FoundryLiteRequestContext;
  requestIdFactory?: () => string;
  onResponse?: (metadata: FoundryLiteResponseMetadata) => void;
};

export type FoundryLiteRequestContext = {
  tenantId?: string;
  userId?: string;
  roles?: string[];
};

export type FoundryLiteRequestInit = RequestInit & { requestId?: string };

export type FoundryLiteResponseMetadata = {
  path: string;
  status: number;
  ok: boolean;
  requestId: string | null;
  errorCode?: string;
  retryable?: boolean;
};

export class FoundryLiteApiError extends Error {
  status: number;
  code: string;
  details: Record<string, unknown>;
  requestId: string | null;
  retryable: boolean;

  constructor(
    status: number,
    code: string,
    message: string,
    details: Record<string, unknown>,
    requestId: string | null,
    retryable: boolean,
  ) {
    super(message);
    this.name = "FoundryLiteApiError";
    this.status = status;
    this.code = code;
    this.details = details;
    this.requestId = requestId;
    this.retryable = retryable;
  }
};

export type FoundryLiteObject<ApiName extends string, Properties> = {
  objectType: ApiName;
  objectId: string;
  objectVersion: number;
  properties: Properties;
  sourceDatasetVersionId?: string | null;
  explain?: { sourceRunChain?: Array<Record<string, unknown>>; propertyLineage?: Array<Record<string, unknown>>; lateDataBadge?: Record<string, unknown> | null };
};

export type ObjectFilter = Record<string, unknown>;
export type ObjectQueryRequest = { filter?: ObjectFilter; orderBy?: Array<Record<string, string>>; limit?: number; cursor?: string | null; search?: string | null };
export type ObjectQueryResult<Item> = { items: Item[]; nextCursor: string | null };
export type ActionApplyResponse = { status: string; actionRunId?: string; object?: Record<string, unknown> };
export type ActionWritebackReconciliationRequest = {
  remoteStatus: "succeeded";
  remoteResourceId: string;
};
export type ActionWritebackReconciliationResult = {
  actionRunId: string;
  writebackId: string;
  status: string;
  remoteStatus: string;
  remoteResourceId: string;
  objectEditId?: string;
  newObjectVersion?: number;
  alreadyReconciled?: boolean;
};
export type RuntimeRunType =
  | "sync"
  | "transform"
  | "index"
  | "action"
  | "action_writeback"
  | "materialization"
  | "outbox"
  | "dead_letter"
  | "audit";
export type RuntimeRunLink = {
  runType: RuntimeRunType;
  runId: string;
  relation: string;
  resourceType: string;
  resourceId: string;
  status: string | null;
  operationPath: string;
};
export type ObservabilityDetectorType =
  | "flow_interruption"
  | "lag"
  | "skew"
  | "slo"
  | "detector_failure";
export type ObservabilitySeverity = "info" | "warning" | "critical";
export type ObservabilityIncidentStatus = "active" | "suppressed";
export type ObservabilityDetectorConfig = {
  detectorId: string;
  detectorType: ObservabilityDetectorType;
  configVersion: string;
  owner: string;
  severity: ObservabilitySeverity;
  runType?: RuntimeRunType;
  resourceType?: string;
  resourceId?: string;
  expectedCadenceSeconds?: number;
  thresholdSeconds?: number;
  thresholdEvents?: number;
  thresholdRatio?: number;
  cooldownSeconds?: number;
  seasonalityBaseline?: Record<string, unknown>;
};
export type ObservabilityIncident = {
  id: string;
  detectorId: string;
  detectorType: ObservabilityDetectorType;
  configVersion: string;
  status: ObservabilityIncidentStatus;
  severity: ObservabilitySeverity;
  owner: string;
  message: string;
  dedupeKey: string;
  firstObservedAt: string;
  lastObservedAt: string;
  evidence: Record<string, unknown>;
  evidenceLinks: RuntimeRunLink[];
  threshold: Record<string, unknown>;
};
export type ObservabilityReport = {
  generatedAt: string;
  configurationVersion: string;
  activeIncidents: ObservabilityIncident[];
  suppressedIncidents: ObservabilityIncident[];
  summary: Record<string, unknown>;
};
export type ObservabilityDetectRequest = {
  configs: ObservabilityDetectorConfig[];
  previousIncidents?: ObservabilityIncident[];
  observedAt?: string | null;
};
export type BackupRestoreVersionStatus = "valid" | "missing" | "corrupt";
export type BackupRestorePreflightStatus = "ready" | "blocked";
export type BackupRestoreManifestIssue = {
  code: string;
  datasetRef: string;
  datasetId: string;
  versionId: string;
  manifestUri: string;
  message: string;
  details: Record<string, unknown>;
};
export type BackupRestoreDatasetVersion = {
  datasetRef: string;
  datasetId: string;
  branch: string;
  versionId: string;
  versionNumber: number;
  manifestUri: string;
  rowCount: number;
  byteSize: number;
  storageProfile: string;
  manifestFileCount: number;
  manifestRowCount: number;
  manifestByteSize: number;
  manifestContentHashes: string[];
  status: BackupRestoreVersionStatus;
  issue: BackupRestoreManifestIssue | null;
};
export type BackupRestoreIndexPointer = {
  objectTypeId: string;
  objectTypeApiName: string;
  activeIndexVersion: string;
};
export type BackupRestorePreflightReport = {
  generatedAt: string;
  tenantId: string;
  backupId: string;
  status: BackupRestorePreflightStatus;
  datasetVersions: BackupRestoreDatasetVersion[];
  issues: BackupRestoreManifestIssue[];
  activeIndexPointers: BackupRestoreIndexPointer[];
  highWatermarks: Record<string, unknown>;
  temporalStrategy: Record<string, unknown>;
  searchRebuild: Record<string, unknown>;
  restoreTrafficGate: Record<string, unknown>;
  summary: Record<string, unknown>;
};
export type BackupRestorePreflightRequest = {
  backupId?: string | null;
};
export type BackupRestoreModeStatus = "inactive" | "paused" | "blocked" | "resume_approved";
export type BackupRestoreModeReport = {
  generatedAt: string;
  tenantId: string;
  restoreId: string;
  backupId: string;
  status: BackupRestoreModeStatus;
  preflightStatus: string;
  is_write_traffic_paused: boolean;
  is_outbox_publisher_paused: boolean;
  is_serving_traffic_open: boolean;
  is_post_restore_validation_required: boolean;
  is_operator_approval_required: boolean;
  blockingIssueCount: number;
  reason: string;
  highWatermarks: Record<string, unknown>;
  summary: Record<string, unknown>;
};
export type BackupRestoreModeStartRequest = {
  backupId?: string | null;
  restoreId?: string | null;
};
export type BackupRestoreResumeApprovalRequest = {
  validationId?: string | null;
};
export type DeadLetterRecordStatus =
  | "QUARANTINED"
  | "REPLAY_REQUESTED"
  | "REPLAYING"
  | "RESOLVED"
  | "DISCARDED";
export type DeadLetterRecordReplayStatus =
  | "NOT_REQUESTED"
  | "REQUESTED"
  | "REPLAYING"
  | "SUCCEEDED"
  | "FAILED"
  | "DISCARDED";
export type DeadLetterRecord = {
  id: string;
  source_event_id: string;
  source_dataset_version_id: string | null;
  source_run_id: string | null;
  payload: Record<string, unknown>;
  payload_hash: string;
  schema_version: number | null;
  transform_version: string | null;
  error_kind: string;
  error_message: string;
  event_time: string | null;
  ingested_at: string;
  first_failed_at: string;
  attempts: number;
  status: DeadLetterRecordStatus;
  replay_status: DeadLetterRecordReplayStatus;
  replay_run_id: string | null;
  replay_idempotency_key: string | null;
  replay_requested_at: string | null;
  discarded_at: string | null;
  backfill_plan: Record<string, unknown> | null;
  is_closed_partition_affected: boolean;
  metadata: Record<string, unknown>;
};
export type DeadLetterRecordRetryResult = {
  deadLetterRecordId: string;
  status: DeadLetterRecordStatus;
  replayStatus: DeadLetterRecordReplayStatus;
  replayRunId: string;
  originDeadLetterRecordId: string;
  is_idempotent_replay: boolean;
  replayDatasetVersionId: string | null;
  rowCount: number | null;
  error: Record<string, unknown> | null;
  downstreamBackfillPlan: Record<string, unknown>;
};
export type DeadLetterRecordBulkRetryFailure = {
  deadLetterRecordId: string;
  code: string;
  message: string;
  details: Record<string, unknown>;
};
export type DeadLetterRecordBulkRetryResult = {
  status: "SUCCEEDED" | "PARTIAL_SUCCESS" | "FAILED";
  items: DeadLetterRecordRetryResult[];
  failedItems: DeadLetterRecordBulkRetryFailure[];
  succeededCount: number;
  failedCount: number;
};
export type DeadLetterRecordDiscardResult = {
  deadLetterRecordId: string;
  status: DeadLetterRecordStatus;
  replayStatus: DeadLetterRecordReplayStatus;
  discardedAt: string;
};
export type IcebergMaintenancePolicy = {
  small_file_threshold_bytes: number;
  file_count_threshold: number;
  read_amplification_threshold: number;
  retention_min_snapshots: number;
};
export type IcebergMaintenanceSnapshot = {
  snapshot_id: number;
  version_id: string | null;
  manifest_uri: string;
  file_count: number;
  row_count: number;
  total_bytes: number;
  average_file_size_bytes: number;
  read_amplification: number;
  is_current: boolean;
  is_protected: boolean;
  protected_by: string[];
  reason_codes: string[];
};
export type IcebergMaintenancePlan = {
  dataset_ref: string;
  dataset_id: string;
  branch: string;
  storage_profile: string;
  table_identifier: string;
  current_snapshot_id: number | null;
  policy: IcebergMaintenancePolicy;
  snapshots: IcebergMaintenanceSnapshot[];
  compaction_candidates: IcebergMaintenanceSnapshot[];
  orphan_snapshots: IcebergMaintenanceSnapshot[];
  protected_snapshot_ids: number[];
  retained_snapshot_ids: number[];
  deletable_snapshot_ids: number[];
  status: string;
};
export type ProductWorkflowStatus =
  | "queued"
  | "running"
  | "succeeded"
  | "failed"
  | "cancelled";
export type ProductWorkflowRun = {
  workflowRunId: string;
  workflowName: string;
  workflowProfile: string;
  status: ProductWorkflowStatus;
  idempotencyKey: string;
  foundryRunId: string | null;
  operationPath: string | null;
  output: Record<string, unknown>;
  error: Record<string, unknown> | null;
  auditEventId?: string | null;
};
export type ConnectorSyncWorkflowStartRequest = {
  datasetRef: string;
  connectorName: string;
  resourceName: string;
  syncName?: string | null;
};

export type OrderProperties = {
  orderId: string;
  customerId: string;
  status?: string;
  amount?: number;
  margin?: number | string;
  riskScore?: number;
  operatorNote?: string;
};
export type Order = FoundryLiteObject<"Order", OrderProperties>;

export type CustomerProperties = {
  customerId: string;
  name?: string;
  segment?: string;
  region?: string;
  riskScore?: number;
  approvedOrderCount?: number;
};
export type Customer = FoundryLiteObject<"Customer", CustomerProperties>;

export type ApproveOrderParams = {
  reason: string;
};
export type ApproveOrderApplyRequest = {
  objectId: string;
  expectedObjectVersion: number;
  params: ApproveOrderParams;
  idempotencyKey?: string;
};

export type FoundryLiteGeneratedClient = {
  request<T = unknown>(path: string, init?: FoundryLiteRequestInit): Promise<T>;
  objects: {
    Order: {
      get(id: string, options?: { explain?: boolean }): Promise<Order>;
      query(payload?: ObjectQueryRequest): Promise<ObjectQueryResult<Order>>;
    };
    Customer: {
      get(id: string, options?: { explain?: boolean }): Promise<Customer>;
      query(payload?: ObjectQueryRequest): Promise<ObjectQueryResult<Customer>>;
    };
  };
  actions: {
    ApproveOrder: {
      apply(payload: ApproveOrderApplyRequest): Promise<ActionApplyResponse>;
    };
  };
  operations: {
    backupRestore: {
      preflight(payload?: BackupRestorePreflightRequest): Promise<BackupRestorePreflightReport>;
      startRestoreMode(payload?: BackupRestoreModeStartRequest): Promise<BackupRestoreModeReport>;
      restoreModeStatus(restoreId: string): Promise<BackupRestoreModeReport>;
      approveResume(restoreId: string, payload?: BackupRestoreResumeApprovalRequest): Promise<BackupRestoreModeReport>;
    };
    deadLetterRecords: {
      list(filters?: { status?: DeadLetterRecordStatus }): Promise<DeadLetterRecord[]>;
      get(id: string): Promise<DeadLetterRecord>;
      retry(id: string, options: { idempotencyKey: string }): Promise<DeadLetterRecordRetryResult>;
      bulkRetry(ids: string[], options: { idempotencyKey: string }): Promise<DeadLetterRecordBulkRetryResult>;
      discard(id: string): Promise<DeadLetterRecordDiscardResult>;
    };
    icebergMaintenance: {
      plan(datasetRef: string, options?: IcebergMaintenancePlanOptions): Promise<IcebergMaintenancePlan>;
    };
    observability: {
      detect(payload: ObservabilityDetectRequest): Promise<ObservabilityReport>;
    };
    reconciliation: {
      resolve(writebackId: string, payload: ActionWritebackReconciliationRequest): Promise<ActionWritebackReconciliationResult>;
    };
    workflows: {
      startConnectorSync(payload: ConnectorSyncWorkflowStartRequest, options: { idempotencyKey: string }): Promise<ProductWorkflowRun>;
      get(workflowRunId: string): Promise<ProductWorkflowRun>;
    };
  };
};

export type IcebergMaintenancePlanOptions = {
  branch?: string;
  smallFileThresholdBytes?: number;
  fileCountThreshold?: number;
  readAmplificationThreshold?: number;
  retentionMinSnapshots?: number;
};

export function idempotencyKey(actionName: string, objectId: string): string {
  return `${actionName}-${objectId}-${Date.now()}`;
}

export function createRequestId(scope: string = "sdk"): string {
  return `${scope}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

export function requestContextHeaders(
  context: FoundryLiteRequestContext = {},
): Record<string, string> {
  const headers: Record<string, string> = {};
  if (context.tenantId) headers["X-Tenant-ID"] = context.tenantId;
  if (context.userId) headers["X-User-ID"] = context.userId;
  if (context.roles?.length) headers["X-Roles"] = context.roles.join(",");
  return headers;
}

function retryableFor(status: number, code: string): boolean {
  return status === 408 || status === 429 || status >= 500 || code === "EXTERNAL_SYSTEM_ERROR";
}

function errorPayload(body: unknown): Record<string, unknown> {
  if (typeof body !== "object" || body === null) return {};
  const detail = (body as { detail?: unknown }).detail;
  const source = typeof detail === "object" && detail !== null ? detail : body;
  return source as Record<string, unknown>;
}

function apiErrorFromResponse(
  body: unknown,
  status: number,
  requestId: string | null,
): FoundryLiteApiError {
  const payload = errorPayload(body);
  const code = typeof payload.code === "string" ? payload.code : "HTTP_ERROR";
  const message = typeof payload.message === "string" ? payload.message : "Request failed";
  const details = typeof payload.details === "object" && payload.details !== null ? payload.details : {};
  const errorRequestId = typeof payload.request_id === "string" ? payload.request_id : requestId;
  return new FoundryLiteApiError(
    status,
    code,
    message,
    details as Record<string, unknown>,
    errorRequestId,
    retryableFor(status, code),
  );
}

export function normalizeFoundryLiteError(error: unknown): FoundryLiteApiError {
  if (error instanceof FoundryLiteApiError) return error;
  const message = error instanceof Error ? error.message : "Network request failed";
  return new FoundryLiteApiError(0, "NETWORK_ERROR", message, {}, null, true);
}

export function isRetryableFoundryLiteError(error: unknown): boolean {
  return normalizeFoundryLiteError(error).retryable;
}

export function expectedObjectVersion(object: { objectVersion: number }): number {
  return object.objectVersion;
}

export function createFoundryLiteClient(clientOptions: FoundryLiteClientOptions): FoundryLiteGeneratedClient {
  async function request<T>(path: string, init?: FoundryLiteRequestInit): Promise<T> {
    const fetcher = clientOptions.fetchImpl ?? fetch;
    const { requestId: explicitRequestId, ...requestInit } = init ?? {};
    const requestId = explicitRequestId ?? clientOptions.requestIdFactory?.() ?? createRequestId("sdk");
    const response = await fetcher(`${clientOptions.baseUrl}${path}`, {
      ...requestInit,
      headers: {
        ...requestContextHeaders(clientOptions.context ?? {}),
        "X-Request-ID": requestId,
        ...(clientOptions.token ? { Authorization: `Bearer ${clientOptions.token}` } : {}),
        ...(clientOptions.headers ?? {}),
        ...(requestInit.headers ?? {}),
      },
    });
    const body = await response.json().catch(() => ({}));
    const responseRequestId = response.headers.get("X-Request-ID") ?? requestId;
    if (!response.ok) {
      const error = apiErrorFromResponse(body, response.status, responseRequestId);
      clientOptions.onResponse?.({
        path,
        status: response.status,
        ok: false,
        requestId: error.requestId,
        errorCode: error.code,
        retryable: error.retryable,
      });
      throw error;
    }
    clientOptions.onResponse?.({ path, status: response.status, ok: true, requestId: responseRequestId });
    return body as T;
  }

  return {
    request,
    objects: {
      Order: {
        get: (id: string, options?: { explain?: boolean }) => {
          const suffix = options?.explain ? '?explain=true' : '';
          return request<Order>(`/api/objects/Order/${encodeURIComponent(id)}${suffix}`);
        },
        query: (payload: ObjectQueryRequest = {}) =>
          request<ObjectQueryResult<Order>>(`/api/objects/Order/query`, {
            method: "POST",
            headers: { 'Content-Type': 'application/json', 'X-Foundry-Lite-Object': "Order" },
            body: JSON.stringify(payload),
          }),
      },
      Customer: {
        get: (id: string, options?: { explain?: boolean }) => {
          const suffix = options?.explain ? '?explain=true' : '';
          return request<Customer>(`/api/objects/Customer/${encodeURIComponent(id)}${suffix}`);
        },
        query: (payload: ObjectQueryRequest = {}) =>
          request<ObjectQueryResult<Customer>>(`/api/objects/Customer/query`, {
            method: "POST",
            headers: { 'Content-Type': 'application/json', 'X-Foundry-Lite-Object': "Customer" },
            body: JSON.stringify(payload),
          }),
      },
    },
    actions: {
      ApproveOrder: {
        apply: (payload: ApproveOrderApplyRequest) =>
          request<ActionApplyResponse>(`/api/actions/ApproveOrder/apply`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "Idempotency-Key": payload.idempotencyKey ?? idempotencyKey(
                "ApproveOrder",
                payload.objectId,
              ),
            },
            body: JSON.stringify({
              target: { objectType: "Order", objectId: payload.objectId },
              expectedObjectVersion: payload.expectedObjectVersion,
              params: payload.params,
            }),
          }),
      },
    },
    operations: {
      backupRestore: {
        preflight: (payload: BackupRestorePreflightRequest = {}) =>
          request<BackupRestorePreflightReport>(`/api/operations/backup-restore/preflight`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          }),
        startRestoreMode: (payload: BackupRestoreModeStartRequest = {}) =>
          request<BackupRestoreModeReport>(`/api/operations/backup-restore/restore-mode/start`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          }),
        restoreModeStatus: (restoreId: string) =>
          request<BackupRestoreModeReport>(
            `/api/operations/backup-restore/restore-mode/${encodeURIComponent(restoreId)}`,
          ),
        approveResume: (restoreId: string, payload: BackupRestoreResumeApprovalRequest = {}) =>
          request<BackupRestoreModeReport>(
            `/api/operations/backup-restore/restore-mode/${encodeURIComponent(restoreId)}/approve-resume`,
            {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify(payload),
            },
          ),
      },
      deadLetterRecords: {
        list: (filters: { status?: DeadLetterRecordStatus } = {}) => {
          const suffix = filters.status ? `?status=${encodeURIComponent(filters.status)}` : '';
          return request<DeadLetterRecord[]>(`/api/operations/dead-letter-records${suffix}`);
        },
        get: (id: string) =>
          request<DeadLetterRecord>(`/api/operations/dead-letter-records/${encodeURIComponent(id)}`),
        retry: (id: string, options: { idempotencyKey: string }) =>
          request<DeadLetterRecordRetryResult>(
            `/api/operations/dead-letter-records/${encodeURIComponent(id)}/retry`,
            {
              method: "POST",
              headers: { "Idempotency-Key": options.idempotencyKey },
            },
          ),
        bulkRetry: (ids: string[], options: { idempotencyKey: string }) =>
          request<DeadLetterRecordBulkRetryResult>(`/api/operations/dead-letter-records/bulk-retry`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "Idempotency-Key": options.idempotencyKey,
            },
            body: JSON.stringify({ ids }),
          }),
        discard: (id: string) =>
          request<DeadLetterRecordDiscardResult>(
            `/api/operations/dead-letter-records/${encodeURIComponent(id)}/discard`,
            { method: "POST" },
          ),
      },
      icebergMaintenance: {
        plan: (datasetRef: string, options: IcebergMaintenancePlanOptions = {}) => {
          const params = new URLSearchParams();
          if (options.branch) params.set('branch', options.branch);
          if (options.smallFileThresholdBytes !== undefined) {
            params.set('smallFileThresholdBytes', String(options.smallFileThresholdBytes));
          }
          if (options.fileCountThreshold !== undefined) {
            params.set('fileCountThreshold', String(options.fileCountThreshold));
          }
          if (options.readAmplificationThreshold !== undefined) {
            params.set('readAmplificationThreshold', String(options.readAmplificationThreshold));
          }
          if (options.retentionMinSnapshots !== undefined) {
            params.set('retentionMinSnapshots', String(options.retentionMinSnapshots));
          }
          const suffix = params.toString() ? `?${params.toString()}` : '';
          return request<IcebergMaintenancePlan>(
            `/api/operations/maintenance/iceberg/${encodeURIComponent(datasetRef)}/plan${suffix}`,
            { method: "POST" },
          );
        },
      },
      observability: {
        detect: (payload: ObservabilityDetectRequest) =>
          request<ObservabilityReport>(`/api/operations/observability/detect`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          }),
      },
      reconciliation: {
        resolve: (writebackId: string, payload: ActionWritebackReconciliationRequest) =>
          request<ActionWritebackReconciliationResult>(
            `/api/operations/reconciliation/${encodeURIComponent(writebackId)}/resolve`,
            {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify(payload),
            },
          ),
      },
      workflows: {
        startConnectorSync: (payload: ConnectorSyncWorkflowStartRequest, options: { idempotencyKey: string }) =>
          request<ProductWorkflowRun>(`/api/operations/workflows/connector-sync/start`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "Idempotency-Key": options.idempotencyKey,
            },
            body: JSON.stringify(payload),
          }),
        get: (workflowRunId: string) =>
          request<ProductWorkflowRun>(`/api/operations/workflows/${encodeURIComponent(workflowRunId)}`),
      },
    },
  };
}

