/* generated by scripts/generate_sdk_ts.py; do not edit by hand */
export const ONTOLOGY_CONTRACT_FINGERPRINT = "a622ceca207f76d4";
export const SDK_CLIENT_SURFACE = {"actions":{"ApproveOrder":["apply"]},"helpers":["createFoundryLiteClient","expectedObjectVersion","idempotencyKey"],"objects":{"Customer":["get","query"],"Order":["get","query"]}};

export type FoundryLiteClientOptions = {
  baseUrl: string;
  headers?: Record<string, string>;
  token?: string;
  fetchImpl?: typeof fetch;
};

export type FoundryLiteObject<ApiName extends string, Properties> = {
  objectType: ApiName;
  objectId: string;
  objectVersion: number;
  properties: Properties;
  sourceDatasetVersionId?: string | null;
  explain?: { sourceRunChain?: Array<Record<string, unknown>> };
};

export type ObjectFilter = Record<string, unknown>;
export type ObjectQueryRequest = { filter?: ObjectFilter; orderBy?: Array<Record<string, string>>; limit?: number; cursor?: string | null; search?: string | null };
export type ObjectQueryResult<Item> = { items: Item[]; nextCursor: string | null };
export type ActionApplyResponse = { status: string; actionRunId?: string; object?: Record<string, unknown> };

export type OrderProperties = {
  orderId: string;
  customerId: string;
  status?: string;
  amount?: number;
  margin?: number | string;
  riskScore?: number;
  operatorNote?: string;
};
export type Order = FoundryLiteObject<"Order", OrderProperties>;

export type CustomerProperties = {
  customerId: string;
  name?: string;
  segment?: string;
  region?: string;
  riskScore?: number;
  approvedOrderCount?: number;
};
export type Customer = FoundryLiteObject<"Customer", CustomerProperties>;

export type ApproveOrderParams = {
  reason: string;
};
export type ApproveOrderApplyRequest = {
  objectId: string;
  expectedObjectVersion: number;
  params: ApproveOrderParams;
  idempotencyKey?: string;
};

export type FoundryLiteGeneratedClient = {
  objects: {
    Order: {
      get(id: string, options?: { explain?: boolean }): Promise<Order>;
      query(payload?: ObjectQueryRequest): Promise<ObjectQueryResult<Order>>;
    };
    Customer: {
      get(id: string, options?: { explain?: boolean }): Promise<Customer>;
      query(payload?: ObjectQueryRequest): Promise<ObjectQueryResult<Customer>>;
    };
  };
  actions: {
    ApproveOrder: {
      apply(payload: ApproveOrderApplyRequest): Promise<ActionApplyResponse>;
    };
  };
};

export function idempotencyKey(actionName: string, objectId: string): string {
  return `${actionName}-${objectId}-${Date.now()}`;
}

export function expectedObjectVersion(object: { objectVersion: number }): number {
  return object.objectVersion;
}

export function createFoundryLiteClient(clientOptions: FoundryLiteClientOptions): FoundryLiteGeneratedClient {
  async function request<T>(path: string, init?: RequestInit): Promise<T> {
    const fetcher = clientOptions.fetchImpl ?? fetch;
    const response = await fetcher(`${clientOptions.baseUrl}${path}`, {
      ...init,
      headers: {
        ...(clientOptions.token ? { Authorization: `Bearer ${clientOptions.token}` } : {}),
        ...(clientOptions.headers ?? {}),
        ...(init?.headers ?? {}),
      },
    });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw body;
    }
    return body as T;
  }

  return {
    objects: {
      Order: {
        get: (id: string, options?: { explain?: boolean }) => {
          const suffix = options?.explain ? '?explain=true' : '';
          return request<Order>(`/api/objects/Order/${encodeURIComponent(id)}${suffix}`);
        },
        query: (payload: ObjectQueryRequest = {}) =>
          request<ObjectQueryResult<Order>>(`/api/objects/Order/query`, {
            method: "POST",
            headers: { 'Content-Type': 'application/json', 'X-Foundry-Lite-Object': "Order" },
            body: JSON.stringify(payload),
          }),
      },
      Customer: {
        get: (id: string, options?: { explain?: boolean }) => {
          const suffix = options?.explain ? '?explain=true' : '';
          return request<Customer>(`/api/objects/Customer/${encodeURIComponent(id)}${suffix}`);
        },
        query: (payload: ObjectQueryRequest = {}) =>
          request<ObjectQueryResult<Customer>>(`/api/objects/Customer/query`, {
            method: "POST",
            headers: { 'Content-Type': 'application/json', 'X-Foundry-Lite-Object': "Customer" },
            body: JSON.stringify(payload),
          }),
      },
    },
    actions: {
      ApproveOrder: {
        apply: (payload: ApproveOrderApplyRequest) =>
          request<ActionApplyResponse>(`/api/actions/ApproveOrder/apply`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "Idempotency-Key": payload.idempotencyKey ?? idempotencyKey(
                "ApproveOrder",
                payload.objectId,
              ),
            },
            body: JSON.stringify({
              target: { objectType: "Order", objectId: payload.objectId },
              expectedObjectVersion: payload.expectedObjectVersion,
              params: payload.params,
            }),
          }),
      },
    },
  };
}

