/* generated by scripts/generate_sdk_ts.py; do not edit by hand */
export const ONTOLOGY_CONTRACT_FINGERPRINT = "a622ceca207f76d4";
export const SDK_CLIENT_SURFACE = {"actions":{"ApproveOrder":["apply"]},"datasets":["list","versions","preview","inspect"],"helpers":["actionLockKey","classifyFoundryLiteError","collectCursorPages","createInFlightActionLock","createFoundryLiteClient","createRequestId","expectedObjectVersion","idempotencyKey","isRetryableFoundryLiteError","normalizeFoundryLiteError","requestContextHeaders","retryWithBackoff"],"insights":{"reviews":["list","create","get","assign","decide"]},"materializations":["run"],"objectSets":["list","create","get"],"objects":{"Customer":["get","query"],"Order":["get","query"],"generic":["get","query","links"]},"ontology":["catalog","validate"],"operations":{"backupRestore":["preflight","startRestoreMode","restoreModeStatus","approveResume"],"deadLetterEvents":["retry"],"deadLetterRecords":["list","get","retry","bulkRetry","discard"],"icebergMaintenance":["planReadOnly","plan"],"index":["replayObjectType","replayFailedRun"],"lineage":["get"],"observability":["detect"],"reconciliation":["resolve"],"runs":["list","detail"],"transforms":["retry"],"workflows":["startConnectorSync","get"]},"system":["health"]};

export type FoundryLiteClientOptions = {
  baseUrl: string;
  headers?: Record<string, string>;
  token?: string;
  fetchImpl?: typeof fetch;
  context?: FoundryLiteRequestContext;
  requestIdFactory?: () => string;
  onResponse?: (metadata: FoundryLiteResponseMetadata) => void;
};

export type FoundryLiteRequestContext = {
  tenantId?: string;
  userId?: string;
  roles?: string[];
};

export type FoundryLiteRequestInit = RequestInit & { requestId?: string };

export type FoundryLiteResponseMetadata = {
  path: string;
  status: number;
  ok: boolean;
  requestId: string | null;
  errorCode?: string;
  retryable?: boolean;
};

export class FoundryLiteApiError extends Error {
  status: number;
  code: string;
  details: Record<string, unknown>;
  requestId: string | null;
  retryable: boolean;

  constructor(
    status: number,
    code: string,
    message: string,
    details: Record<string, unknown>,
    requestId: string | null,
    retryable: boolean,
  ) {
    super(message);
    this.name = "FoundryLiteApiError";
    this.status = status;
    this.code = code;
    this.details = details;
    this.requestId = requestId;
    this.retryable = retryable;
  }
};

export type FoundryLiteErrorKind =
  | "permission_denied"
  | "stale_object_version"
  | "conflict"
  | "retryable"
  | "not_found"
  | "validation"
  | "unknown";
export type FoundryLiteErrorClassification = {
  kind: FoundryLiteErrorKind;
  status: number;
  code: string;
  message: string;
  details: Record<string, unknown>;
  requestId: string | null;
  retryable: boolean;
};
export type RetryWithBackoffOptions = {
  maxAttempts?: number;
  baseDelayMs?: number;
  maxDelayMs?: number;
  jitterRatio?: number;
  sleep?: (delayMs: number) => Promise<void>;
  shouldRetry?: (error: FoundryLiteApiError, attempt: number) => boolean;
  onRetry?: (metadata: {
    attempt: number;
    delayMs: number;
    error: FoundryLiteApiError;
  }) => void;
};
export type CursorCollectOptions<TPage, TItem> = {
  initialCursor?: string | null;
  maxPages?: number;
  getItems?: (page: TPage) => TItem[];
  getNextCursor?: (page: TPage) => string | null | undefined;
};
export type InFlightActionLock = {
  run<T>(key: string, task: () => Promise<T>): Promise<T>;
  isLocked(key: string): boolean;
  clear(key?: string): void;
};

export type SystemHealth = { status: string };
export type TabularRow = Record<string, unknown>;
export type Dataset = {
  id: string;
  tenant_id: string;
  namespace: string;
  name: string;
  description: string | null;
  storage_kind: string;
  storage_uri: string | null;
  owner_team: string | null;
  classification: string | null;
  status: string;
  primary_key: string[];
  partition_spec: string[];
  sort_order: string[];
  target_file_size_bytes: number | null;
  created_at: string;
  updated_at: string;
};
export type DatasetVersion = {
  id: string;
  tenant_id: string;
  dataset_id: string;
  branch: string;
  version_number: number;
  transaction_id: string;
  schema_version: number;
  manifest_uri: string;
  row_count: number;
  byte_size: number;
  status: string;
  superseded_by_version_id: string | null;
  created_at: string;
};
export type DatasetManifestFile = {
  uri: string;
  format: string;
  row_count: number;
  byte_size: number;
  content_hash: string;
  partition_values?: Record<string, unknown>;
};
export type DatasetManifest = {
  version_id: string;
  dataset: string;
  branch: string;
  schema_hash: string;
  files: DatasetManifestFile[];
  created_at: string;
  storage_profile: string;
};
export type DatasetInspectionPayload = {
  dataset: string;
  dataset_id: string;
  version: DatasetVersion;
  schema: Record<string, unknown>;
  manifest: DatasetManifest;
};
export type DatasetPreviewOptions = { limit?: number };
export type DatasetInspectOptions = { version?: string };
export type OntologyValidateRequest = { yaml: string };
export type OntologyValidationResult = {
  status: string;
  object_type_count: number;
  link_type_count: number;
  action_type_count: number;
};
export type OntologyCatalogProperty = {
  apiName: string;
  displayName: string;
  dataType: string;
  nullable: boolean;
  indexed: boolean;
  searchable: boolean;
  editable: boolean;
  classification: string | null;
  source: string;
  columnName: string | null;
  editPolicy: string;
  derivation: Record<string, unknown> | null;
};
export type OntologyCatalogAction = {
  apiName: string;
  displayName: string;
  target: string;
  parameterSchema: Record<string, unknown>;
  definition: Record<string, unknown>;
  enabled: boolean;
};
export type OntologyCatalogObject = {
  apiName: string;
  displayName: string;
  description: string | null;
  primaryKeyProperty: string;
  backing: Record<string, unknown>;
  properties: OntologyCatalogProperty[];
  actions: OntologyCatalogAction[];
  config: Record<string, unknown>;
};
export type OntologyCatalogLink = {
  apiName: string;
  displayName: string;
  fromObjectType: string;
  toObjectType: string;
  cardinality: string;
  backing: Record<string, unknown>;
};
export type OntologyCatalog = {
  ontologyVersionId: string;
  versionNumber: number;
  status: string;
  createdAt: string;
  activatedAt: string | null;
  objectTypes: OntologyCatalogObject[];
  linkTypes: OntologyCatalogLink[];
};

export type FoundryLiteObject<ApiName extends string, Properties> = {
  objectType: ApiName;
  objectId: string;
  objectVersion: number;
  properties: Properties;
  sourceDatasetVersionId?: string | null;
  explain?: { sourceRunChain?: Array<Record<string, unknown>>; propertyLineage?: Array<Record<string, unknown>>; lateDataBadge?: Record<string, unknown> | null };
};

export type GenericObject = FoundryLiteObject<string, Record<string, unknown>>;
export type ObjectReference = { objectType: string; objectId: string };
export type ObjectLinkTarget = {
  objectType: string;
  objectId: string;
  properties: Record<string, unknown>;
  targetMissing?: boolean;
};
export type ObjectLinkPayload = {
  linkType: string;
  from: ObjectReference;
  to: ObjectLinkTarget;
  warning?: { type: string; message: string };
};
export type ObjectFilter = Record<string, unknown>;
export type ObjectQueryRequest = { filter?: ObjectFilter; orderBy?: Array<Record<string, string>>; limit?: number; cursor?: string | null; search?: string | null };
export type ObjectQueryResult<Item> = { items: Item[]; nextCursor: string | null };
export type ObjectSetCreateRequest = {
  name: string;
  objectType: string;
  setType: string;
  visibility?: string;
  ids?: string[] | null;
  filter?: Record<string, unknown> | null;
  ttlSeconds?: number | null;
};
export type ObjectSetPayload = {
  id: string;
  name: string;
  objectType: string;
  setType: string;
  definition: Record<string, unknown>;
  visibility: string;
  ownerUserId: string;
  expiresAt: string | null;
  createdAt: string;
  objectIds: string[];
  items?: Array<Record<string, unknown>>;
};
export type ObjectSetQueryResult = { items: ObjectSetPayload[] };
export type InsightReviewStatus = "pending" | "approved" | "rejected";
export type InsightReviewDecision = "approved" | "rejected";
export type InsightReviewPriority = "low" | "normal" | "high";
export type InsightActionProposal = {
  actionApiName?: string;
  targetObjectType?: string;
  targetObjectId?: string;
  expectedObjectVersion?: number;
  params?: Record<string, unknown>;
};
export type InsightReviewCreateRequest = {
  claimId: string;
  claimText: string;
  evidenceObjectIds: string[];
  evidenceRefs: Array<Record<string, unknown>>;
  priority?: InsightReviewPriority;
  assigneeUserId?: string | null;
  actionProposal?: InsightActionProposal | null;
};
export type InsightReviewAssignRequest = { assigneeUserId: string };
export type InsightReviewDecisionRequest = {
  decision: InsightReviewDecision;
  comment?: string | null;
};
export type InsightReviewPayload = {
  id: string;
  claimId: string;
  claimText: string;
  status: InsightReviewStatus;
  priority: InsightReviewPriority;
  assigneeUserId: string | null;
  evidenceObjectIds: string[];
  evidenceRefs: Array<Record<string, unknown>>;
  actionProposal: InsightActionProposal | null;
  createdByUserId: string;
  decision: Record<string, unknown> | null;
  createdAt: string;
  updatedAt: string;
};
export type InsightReviewQueryResult = { items: InsightReviewPayload[] };
export type InsightReviewListFilters = {
  status?: InsightReviewStatus;
  assigneeUserId?: string;
  limit?: number;
};
export type ActionApplyResponse = { status: string; actionRunId?: string; object?: Record<string, unknown> };
export type MaterializationRunResult = {
  dataset_id: string;
  dataset_ref: string;
  transaction_id: string;
  version_id: string;
  version_number: number;
  row_count: number;
  manifest_uri: string;
  schema_hash: string;
};
export type ActionWritebackReconciliationRequest = {
  remoteStatus: "succeeded";
  remoteResourceId: string;
};
export type ActionWritebackReconciliationResult = {
  actionRunId: string;
  writebackId: string;
  status: string;
  remoteStatus: string;
  remoteResourceId: string;
  objectEditId?: string;
  newObjectVersion?: number;
  alreadyReconciled?: boolean;
};
export type RuntimeRunType =
  | "sync"
  | "transform"
  | "index"
  | "action"
  | "action_writeback"
  | "materialization"
  | "outbox"
  | "dead_letter"
  | "workflow"
  | "audit";
export type RuntimeRow = Record<string, unknown>;
export type LineageEdge = {
  id: string;
  tenant_id: string;
  from_resource_type: string;
  from_resource_id: string;
  to_resource_type: string;
  to_resource_id: string;
  relation: string;
  created_by_run_id: string;
  created_at: string;
};
export type RuntimeRunLink = {
  runType: RuntimeRunType;
  runId: string;
  relation: string;
  resourceType: string;
  resourceId: string;
  status: string | null;
  operationPath: string;
};
export type RuntimeRunRelation = {
  id: string;
  tenant_id: string;
  source_run_type: RuntimeRunType;
  source_run_id: string;
  target_run_type: RuntimeRunType;
  target_run_id: string;
  relation: string;
  resource_type: string;
  resource_id: string;
  metadata: Record<string, unknown>;
  created_at: string;
};
export type RuntimeRunQueryFilters = {
  runType?: RuntimeRunType | string;
  status?: string;
  since?: string;
  until?: string;
  limit?: number;
  cursor?: string | null;
};
export type RuntimeRunQueryResult = {
  syncRuns: RuntimeRow[];
  transformRuns: RuntimeRow[];
  indexRuns: RuntimeRow[];
  actionRuns: RuntimeRow[];
  actionWritebacks: RuntimeRow[];
  materializationRuns: RuntimeRow[];
  outboxEvents: RuntimeRow[];
  deadLetterEvents: RuntimeRow[];
  workflowRuns: RuntimeRow[];
  auditEvents: RuntimeRow[];
  objectEdits: RuntimeRow[];
  nextCursor?: string | null;
  nextCursors?: Record<string, string>;
};
export type RuntimeRunDetail = {
  runType: RuntimeRunType;
  runId: string;
  row: RuntimeRow;
  status: string | null;
  errorMessage: string | null;
  error: unknown;
  correlationId: string | null;
  references: Record<string, unknown>;
  investigation: Record<string, unknown>;
  relatedOutboxEvents: RuntimeRow[];
  relatedAuditEvents: RuntimeRow[];
  relatedObjectEdits: RuntimeRow[];
  relatedActionWritebacks: RuntimeRow[];
  runRelations: RuntimeRunRelation[];
  lineageEdges: RuntimeRow[];
  datasetTransaction?: RuntimeRow | null;
  lateData?: Record<string, unknown> | null;
  materialization?: Record<string, unknown> | null;
  downstreamImpact?: Record<string, unknown> | null;
  quality?: Record<string, unknown> | null;
};
export type RuntimeRetryResult = {
  deadLetterEventId: string;
  outboxEventId: string;
  eventType: string;
  payload: Record<string, unknown>;
  status: string;
  materializationResult?: Record<string, unknown>;
};
export type ObjectIndexRebuildResult = {
  index_run_id: string;
  object_type: string;
  rows_read: number;
  objects_upserted: number;
  objects_deleted: number;
  links_upserted: number;
};
export type TransformRetryResult = {
  original_run_id: string;
  transform_run_id: string;
  dataset_id: string;
  dataset_ref: string;
  transaction_id: string;
  version_id: string;
  version_number: number;
  row_count: number;
  manifest_uri: string;
  schema_hash: string;
};
export type ObservabilityDetectorType =
  | "flow_interruption"
  | "lag"
  | "skew"
  | "slo"
  | "detector_failure";
export type ObservabilitySeverity = "info" | "warning" | "critical";
export type ObservabilityIncidentStatus = "active" | "suppressed";
export type ObservabilityDetectorConfig = {
  detectorId: string;
  detectorType: ObservabilityDetectorType;
  configVersion: string;
  owner: string;
  severity: ObservabilitySeverity;
  runType?: RuntimeRunType;
  resourceType?: string;
  resourceId?: string;
  expectedCadenceSeconds?: number;
  thresholdSeconds?: number;
  thresholdEvents?: number;
  thresholdRatio?: number;
  cooldownSeconds?: number;
  seasonalityBaseline?: Record<string, unknown>;
};
export type ObservabilityIncident = {
  id: string;
  detectorId: string;
  detectorType: ObservabilityDetectorType;
  configVersion: string;
  status: ObservabilityIncidentStatus;
  severity: ObservabilitySeverity;
  owner: string;
  message: string;
  dedupeKey: string;
  firstObservedAt: string;
  lastObservedAt: string;
  evidence: Record<string, unknown>;
  evidenceLinks: RuntimeRunLink[];
  threshold: Record<string, unknown>;
};
export type ObservabilityReport = {
  generatedAt: string;
  configurationVersion: string;
  activeIncidents: ObservabilityIncident[];
  suppressedIncidents: ObservabilityIncident[];
  summary: Record<string, unknown>;
};
export type ObservabilityDetectRequest = {
  configs: ObservabilityDetectorConfig[];
  previousIncidents?: ObservabilityIncident[];
  observedAt?: string | null;
};
export type BackupRestoreVersionStatus = "valid" | "missing" | "corrupt";
export type BackupRestorePreflightStatus = "ready" | "blocked";
export type BackupRestoreManifestIssue = {
  code: string;
  datasetRef: string;
  datasetId: string;
  versionId: string;
  manifestUri: string;
  message: string;
  details: Record<string, unknown>;
};
export type BackupRestoreDatasetVersion = {
  datasetRef: string;
  datasetId: string;
  branch: string;
  versionId: string;
  versionNumber: number;
  manifestUri: string;
  rowCount: number;
  byteSize: number;
  storageProfile: string;
  manifestFileCount: number;
  manifestRowCount: number;
  manifestByteSize: number;
  manifestContentHashes: string[];
  status: BackupRestoreVersionStatus;
  issue: BackupRestoreManifestIssue | null;
};
export type BackupRestoreIndexPointer = {
  objectTypeId: string;
  objectTypeApiName: string;
  activeIndexVersion: string;
};
export type BackupRestorePreflightReport = {
  generatedAt: string;
  tenantId: string;
  backupId: string;
  status: BackupRestorePreflightStatus;
  datasetVersions: BackupRestoreDatasetVersion[];
  issues: BackupRestoreManifestIssue[];
  activeIndexPointers: BackupRestoreIndexPointer[];
  highWatermarks: Record<string, unknown>;
  temporalStrategy: Record<string, unknown>;
  searchRebuild: Record<string, unknown>;
  restoreTrafficGate: Record<string, unknown>;
  summary: Record<string, unknown>;
};
export type BackupRestorePreflightRequest = {
  backupId?: string | null;
};
export type BackupRestoreModeStatus = "inactive" | "paused" | "blocked" | "resume_approved";
export type BackupRestoreModeReport = {
  generatedAt: string;
  tenantId: string;
  restoreId: string;
  backupId: string;
  status: BackupRestoreModeStatus;
  preflightStatus: string;
  is_write_traffic_paused: boolean;
  is_outbox_publisher_paused: boolean;
  is_serving_traffic_open: boolean;
  is_post_restore_validation_required: boolean;
  is_operator_approval_required: boolean;
  blockingIssueCount: number;
  reason: string;
  highWatermarks: Record<string, unknown>;
  summary: Record<string, unknown>;
};
export type BackupRestoreModeStartRequest = {
  backupId?: string | null;
  restoreId?: string | null;
};
export type BackupRestoreResumeApprovalRequest = {
  validationId?: string | null;
};
export type DeadLetterRecordStatus =
  | "QUARANTINED"
  | "REPLAY_REQUESTED"
  | "REPLAYING"
  | "RESOLVED"
  | "DISCARDED";
export type DeadLetterRecordReplayStatus =
  | "NOT_REQUESTED"
  | "REQUESTED"
  | "REPLAYING"
  | "SUCCEEDED"
  | "FAILED"
  | "DISCARDED";
export type DeadLetterRecord = {
  id: string;
  source_event_id: string;
  source_dataset_version_id: string | null;
  source_run_id: string | null;
  payload: Record<string, unknown>;
  payload_hash: string;
  schema_version: number | null;
  transform_version: string | null;
  error_kind: string;
  error_message: string;
  event_time: string | null;
  ingested_at: string;
  first_failed_at: string;
  attempts: number;
  status: DeadLetterRecordStatus;
  replay_status: DeadLetterRecordReplayStatus;
  replay_run_id: string | null;
  replay_idempotency_key: string | null;
  replay_requested_at: string | null;
  discarded_at: string | null;
  backfill_plan: Record<string, unknown> | null;
  is_closed_partition_affected: boolean;
  metadata: Record<string, unknown>;
};
export type DeadLetterRecordRetryResult = {
  deadLetterRecordId: string;
  status: DeadLetterRecordStatus;
  replayStatus: DeadLetterRecordReplayStatus;
  replayRunId: string;
  originDeadLetterRecordId: string;
  is_idempotent_replay: boolean;
  replayDatasetVersionId: string | null;
  rowCount: number | null;
  error: Record<string, unknown> | null;
  downstreamBackfillPlan: Record<string, unknown>;
};
export type DeadLetterRecordBulkRetryFailure = {
  deadLetterRecordId: string;
  code: string;
  message: string;
  details: Record<string, unknown>;
};
export type DeadLetterRecordBulkRetryResult = {
  status: "SUCCEEDED" | "PARTIAL_SUCCESS" | "FAILED";
  items: DeadLetterRecordRetryResult[];
  failedItems: DeadLetterRecordBulkRetryFailure[];
  succeededCount: number;
  failedCount: number;
};
export type DeadLetterRecordDiscardResult = {
  deadLetterRecordId: string;
  status: DeadLetterRecordStatus;
  replayStatus: DeadLetterRecordReplayStatus;
  discardedAt: string;
};
export type IcebergMaintenancePolicy = {
  small_file_threshold_bytes: number;
  file_count_threshold: number;
  read_amplification_threshold: number;
  retention_min_snapshots: number;
};
export type IcebergMaintenanceSnapshot = {
  snapshot_id: number;
  version_id: string | null;
  manifest_uri: string;
  file_count: number;
  row_count: number;
  total_bytes: number;
  average_file_size_bytes: number;
  read_amplification: number;
  is_current: boolean;
  is_protected: boolean;
  protected_by: string[];
  reason_codes: string[];
};
export type IcebergMaintenancePlan = {
  dataset_ref: string;
  dataset_id: string;
  branch: string;
  storage_profile: string;
  table_identifier: string;
  current_snapshot_id: number | null;
  policy: IcebergMaintenancePolicy;
  snapshots: IcebergMaintenanceSnapshot[];
  compaction_candidates: IcebergMaintenanceSnapshot[];
  orphan_snapshots: IcebergMaintenanceSnapshot[];
  protected_snapshot_ids: number[];
  retained_snapshot_ids: number[];
  deletable_snapshot_ids: number[];
  status: string;
};
export type ProductWorkflowStatus =
  | "queued"
  | "running"
  | "succeeded"
  | "failed"
  | "cancelled"
  | "requested"
  | "starting"
  | "start_unknown";
export type ProductWorkflowRun = {
  workflowRunId: string;
  workflowName: string;
  workflowProfile: string;
  status: ProductWorkflowStatus;
  idempotencyKey: string;
  foundryRunId: string | null;
  operationPath: string | null;
  output: Record<string, unknown>;
  error: Record<string, unknown> | null;
  auditEventId?: string | null;
};
export type ConnectorSyncWorkflowStartRequest = {
  datasetRef: string;
  connectorName: string;
  resourceName: string;
  syncName?: string | null;
};

export type OrderProperties = {
  orderId: string;
  customerId: string;
  status?: string;
  amount?: number;
  margin?: number | string;
  riskScore?: number;
  operatorNote?: string;
};
export type Order = FoundryLiteObject<"Order", OrderProperties>;

export type CustomerProperties = {
  customerId: string;
  name?: string;
  segment?: string;
  region?: string;
  riskScore?: number;
  approvedOrderCount?: number;
};
export type Customer = FoundryLiteObject<"Customer", CustomerProperties>;

export type ApproveOrderParams = {
  reason: string;
};
export type ApproveOrderApplyRequest = {
  objectId: string;
  expectedObjectVersion: number;
  params: ApproveOrderParams;
  idempotencyKey: string;
};

export type FoundryLiteGeneratedClient = {
  request<T = unknown>(path: string, init?: FoundryLiteRequestInit): Promise<T>;
  system: {
    health(): Promise<SystemHealth>;
  };
  datasets: {
    list(): Promise<Dataset[]>;
    versions(namespace: string, name: string): Promise<DatasetVersion[]>;
    preview(namespace: string, name: string, options?: DatasetPreviewOptions): Promise<TabularRow[]>;
    inspect(namespace: string, name: string, options?: DatasetInspectOptions): Promise<DatasetInspectionPayload>;
  };
  ontology: {
    catalog(): Promise<OntologyCatalog>;
    validate(payload: OntologyValidateRequest): Promise<OntologyValidationResult>;
  };
  insights: {
    reviews: {
      list(filters?: InsightReviewListFilters): Promise<InsightReviewQueryResult>;
      create(payload: InsightReviewCreateRequest, options: { idempotencyKey: string }): Promise<InsightReviewPayload>;
      get(reviewId: string): Promise<InsightReviewPayload>;
      assign(reviewId: string, payload: InsightReviewAssignRequest, options: { idempotencyKey: string }): Promise<InsightReviewPayload>;
      decide(reviewId: string, payload: InsightReviewDecisionRequest, options: { idempotencyKey: string }): Promise<InsightReviewPayload>;
    };
  };
  objects: {
    generic: {
      get(objectType: string, id: string, options?: { explain?: boolean }): Promise<GenericObject>;
      query(objectType: string, payload?: ObjectQueryRequest): Promise<ObjectQueryResult<GenericObject>>;
      links(objectType: string, id: string, linkType: string): Promise<ObjectLinkPayload[]>;
    };
    Order: {
      get(id: string, options?: { explain?: boolean }): Promise<Order>;
      query(payload?: ObjectQueryRequest): Promise<ObjectQueryResult<Order>>;
    };
    Customer: {
      get(id: string, options?: { explain?: boolean }): Promise<Customer>;
      query(payload?: ObjectQueryRequest): Promise<ObjectQueryResult<Customer>>;
    };
  };
  actions: {
    ApproveOrder: {
      apply(payload: ApproveOrderApplyRequest): Promise<ActionApplyResponse>;
    };
  };
  objectSets: {
    list(filters?: { objectType?: string }): Promise<ObjectSetQueryResult>;
    create(payload: ObjectSetCreateRequest): Promise<ObjectSetPayload>;
    get(id: string): Promise<ObjectSetPayload>;
  };
  materializations: {
    run(apiName: string): Promise<MaterializationRunResult>;
  };
  operations: {
    runs: {
      list(filters?: RuntimeRunQueryFilters): Promise<RuntimeRunQueryResult>;
      detail(runType: string, runId: string): Promise<RuntimeRunDetail>;
    };
    backupRestore: {
      preflight(payload?: BackupRestorePreflightRequest): Promise<BackupRestorePreflightReport>;
      startRestoreMode(payload?: BackupRestoreModeStartRequest): Promise<BackupRestoreModeReport>;
      restoreModeStatus(restoreId: string): Promise<BackupRestoreModeReport>;
      approveResume(restoreId: string, payload?: BackupRestoreResumeApprovalRequest): Promise<BackupRestoreModeReport>;
    };
    deadLetterRecords: {
      list(filters?: { status?: DeadLetterRecordStatus }): Promise<DeadLetterRecord[]>;
      get(id: string): Promise<DeadLetterRecord>;
      retry(id: string, options: { idempotencyKey: string }): Promise<DeadLetterRecordRetryResult>;
      bulkRetry(ids: string[], options: { idempotencyKey: string }): Promise<DeadLetterRecordBulkRetryResult>;
      discard(id: string): Promise<DeadLetterRecordDiscardResult>;
    };
    deadLetterEvents: {
      retry(id: string): Promise<RuntimeRetryResult>;
    };
    icebergMaintenance: {
      planReadOnly(datasetRef: string, options?: IcebergMaintenancePlanOptions): Promise<IcebergMaintenancePlan>;
      plan(datasetRef: string, options?: IcebergMaintenancePlanOptions): Promise<IcebergMaintenancePlan>;
    };
    index: {
      replayObjectType(objectType: string): Promise<ObjectIndexRebuildResult>;
      replayFailedRun(runId: string): Promise<ObjectIndexRebuildResult>;
    };
    lineage: {
      get(resourceId: string): Promise<LineageEdge[]>;
    };
    observability: {
      detect(payload: ObservabilityDetectRequest): Promise<ObservabilityReport>;
    };
    reconciliation: {
      resolve(writebackId: string, payload: ActionWritebackReconciliationRequest): Promise<ActionWritebackReconciliationResult>;
    };
    transforms: {
      retry(runId: string): Promise<TransformRetryResult>;
    };
    workflows: {
      startConnectorSync(payload: ConnectorSyncWorkflowStartRequest, options: { idempotencyKey: string }): Promise<ProductWorkflowRun>;
      get(workflowRunId: string): Promise<ProductWorkflowRun>;
    };
  };
};

export type IcebergMaintenancePlanOptions = {
  branch?: string;
  smallFileThresholdBytes?: number;
  fileCountThreshold?: number;
  readAmplificationThreshold?: number;
  retentionMinSnapshots?: number;
};

export function idempotencyKey(actionName: string, objectId: string): string {
  return `${actionName}-${objectId}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

export function createRequestId(scope: string = "sdk"): string {
  return `${scope}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

export function requestContextHeaders(
  context: FoundryLiteRequestContext = {},
): Record<string, string> {
  const headers: Record<string, string> = {};
  if (context.tenantId) headers["X-Tenant-ID"] = context.tenantId;
  if (context.userId) headers["X-User-ID"] = context.userId;
  if (context.roles?.length) headers["X-Roles"] = context.roles.join(",");
  return headers;
}

function requireIdempotencyKey(value: string | undefined, operationName: string): string {
  if (value) return value;
  throw new FoundryLiteApiError(
    0,
    "MISSING_IDEMPOTENCY_KEY",
    `${operationName} requires a caller-supplied idempotency key`,
    { operationName },
    null,
    false,
  );
}

function retryableFor(status: number, code: string): boolean {
  return status === 408 || status === 429 || status >= 500 || code === "EXTERNAL_SYSTEM_ERROR";
}

function errorPayload(body: unknown): Record<string, unknown> {
  if (typeof body !== "object" || body === null) return {};
  const detail = (body as { detail?: unknown }).detail;
  const source = typeof detail === "object" && detail !== null ? detail : body;
  return source as Record<string, unknown>;
}

function apiErrorFromResponse(
  body: unknown,
  status: number,
  requestId: string | null,
): FoundryLiteApiError {
  const payload = errorPayload(body);
  const code = typeof payload.code === "string" ? payload.code : "HTTP_ERROR";
  const message = typeof payload.message === "string" ? payload.message : "Request failed";
  const details = typeof payload.details === "object" && payload.details !== null ? payload.details : {};
  const errorRequestId = typeof payload.request_id === "string" ? payload.request_id : requestId;
  return new FoundryLiteApiError(
    status,
    code,
    message,
    details as Record<string, unknown>,
    errorRequestId,
    retryableFor(status, code),
  );
}

export function normalizeFoundryLiteError(error: unknown): FoundryLiteApiError {
  if (error instanceof FoundryLiteApiError) return error;
  const message = error instanceof Error ? error.message : "Network request failed";
  return new FoundryLiteApiError(0, "NETWORK_ERROR", message, {}, null, true);
}

export function isRetryableFoundryLiteError(error: unknown): boolean {
  return normalizeFoundryLiteError(error).retryable;
}

export function expectedObjectVersion(object: { objectVersion: number }): number {
  return object.objectVersion;
}

export function classifyFoundryLiteError(error: unknown): FoundryLiteErrorClassification {
  const normalized = normalizeFoundryLiteError(error);
  let kind: FoundryLiteErrorKind = "unknown";
  if (normalized.code === "PERMISSION_DENIED") kind = "permission_denied";
  else if (normalized.code === "NOT_FOUND") kind = "not_found";
  else if (normalized.code === "VALIDATION_FAILED") kind = "validation";
  else if (normalized.code === "CONFLICT" && looksLikeStaleObjectVersion(normalized)) {
    kind = "stale_object_version";
  } else if (normalized.code === "CONFLICT") kind = "conflict";
  else if (normalized.retryable) kind = "retryable";
  return {
    kind,
    status: normalized.status,
    code: normalized.code,
    message: normalized.message,
    details: normalized.details,
    requestId: normalized.requestId,
    retryable: normalized.retryable,
  };
}

function looksLikeStaleObjectVersion(error: FoundryLiteApiError): boolean {
  return Boolean(
    error.details.expectedObjectVersion !== undefined ||
      error.details.actualObjectVersion !== undefined ||
      error.details.objectVersion !== undefined ||
      error.message.toLowerCase().includes("object version")
  );
}

export function actionLockKey(actionName: string, objectId: string): string {
  return `${actionName}:${objectId}`;
}

export function createInFlightActionLock(): InFlightActionLock {
  const inFlight = new Map<string, Promise<unknown>>();
  return {
    run<T>(key: string, task: () => Promise<T>): Promise<T> {
      if (inFlight.has(key)) return inFlight.get(key) as Promise<T>;
      const promise = Promise.resolve().then(task).finally(() => {
        if (inFlight.get(key) === promise) inFlight.delete(key);
      });
      inFlight.set(key, promise);
      return promise;
    },
    isLocked(key: string): boolean {
      return inFlight.has(key);
    },
    clear(key?: string): void {
      if (key === undefined) inFlight.clear();
      else inFlight.delete(key);
    },
  };
}

function defaultSleep(delayMs: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, delayMs));
}

function retryDelayMs(attempt: number, options: RetryWithBackoffOptions): number {
  const base = options.baseDelayMs ?? 250;
  const max = options.maxDelayMs ?? 4000;
  const jitterRatio = options.jitterRatio ?? 0.2;
  const exponential = Math.min(max, base * 2 ** Math.max(0, attempt - 1));
  const jitter = exponential * jitterRatio * Math.random();
  return Math.round(exponential + jitter);
}

export async function retryWithBackoff<T>(
  operation: () => Promise<T>,
  options: RetryWithBackoffOptions = {},
): Promise<T> {
  const maxAttempts = options.maxAttempts ?? 3;
  let attempt = 0;
  while (true) {
    try {
      return await operation();
    } catch (error) {
      attempt += 1;
      const normalized = normalizeFoundryLiteError(error);
      const shouldRetry = options.shouldRetry?.(normalized, attempt) ?? normalized.retryable;
      if (!shouldRetry || attempt >= maxAttempts) throw error;
      const delayMs = retryDelayMs(attempt, options);
      options.onRetry?.({ attempt, delayMs, error: normalized });
      await (options.sleep ?? defaultSleep)(delayMs);
    }
  }
}

export async function collectCursorPages<TPage, TItem = unknown>(
  fetchPage: (cursor: string | null) => Promise<TPage>,
  options: CursorCollectOptions<TPage, TItem> = {},
): Promise<TItem[]> {
  const getItems = options.getItems ?? ((page) => (page as { items?: TItem[] }).items ?? []);
  const getNextCursor = options.getNextCursor ?? (
    (page) => (page as { nextCursor?: string | null }).nextCursor ?? null
  );
  const maxPages = options.maxPages ?? 100;
  const items: TItem[] = [];
  let cursor = options.initialCursor ?? null;
  for (let pageNumber = 0; pageNumber < maxPages; pageNumber += 1) {
    const page = await fetchPage(cursor);
    items.push(...getItems(page));
    cursor = getNextCursor(page) ?? null;
    if (!cursor) return items;
  }
  throw new FoundryLiteApiError(
    0,
    "CURSOR_LIMIT_EXCEEDED",
    "Cursor pagination exceeded maxPages",
    { maxPages },
    null,
    false,
  );
}

export function createFoundryLiteClient(clientOptions: FoundryLiteClientOptions): FoundryLiteGeneratedClient {
  async function request<T>(path: string, init?: FoundryLiteRequestInit): Promise<T> {
    const fetcher = clientOptions.fetchImpl ?? fetch;
    const { requestId: explicitRequestId, ...requestInit } = init ?? {};
    const requestId = explicitRequestId ?? clientOptions.requestIdFactory?.() ?? createRequestId("sdk");
    const response = await fetcher(`${clientOptions.baseUrl}${path}`, {
      ...requestInit,
      headers: {
        ...requestContextHeaders(clientOptions.context ?? {}),
        "X-Request-ID": requestId,
        ...(clientOptions.token ? { Authorization: `Bearer ${clientOptions.token}` } : {}),
        ...(clientOptions.headers ?? {}),
        ...(requestInit.headers ?? {}),
      },
    });
    const body = await response.json().catch(() => ({}));
    const responseRequestId = response.headers.get("X-Request-ID") ?? requestId;
    if (!response.ok) {
      const error = apiErrorFromResponse(body, response.status, responseRequestId);
      clientOptions.onResponse?.({
        path,
        status: response.status,
        ok: false,
        requestId: error.requestId,
        errorCode: error.code,
        retryable: error.retryable,
      });
      throw error;
    }
    clientOptions.onResponse?.({ path, status: response.status, ok: true, requestId: responseRequestId });
    return body as T;
  }

  return {
    request,
    system: {
      health: () => request<SystemHealth>(`/healthz`),
    },
    datasets: {
      list: () => request<Dataset[]>(`/api/datasets`),
      versions: (namespace: string, name: string) =>
        request<DatasetVersion[]>(
          `/api/datasets/${encodeURIComponent(namespace)}/${encodeURIComponent(name)}/versions`,
        ),
      preview: (namespace: string, name: string, options: DatasetPreviewOptions = {}) => {
        const params = new URLSearchParams();
        if (options.limit !== undefined) params.set('limit', String(options.limit));
        const suffix = params.toString() ? `?${params.toString()}` : '';
        return request<TabularRow[]>(
          `/api/datasets/${encodeURIComponent(namespace)}/${encodeURIComponent(name)}/preview${suffix}`,
        );
      },
      inspect: (namespace: string, name: string, options: DatasetInspectOptions = {}) => {
        const params = new URLSearchParams();
        if (options.version !== undefined) params.set('version', String(options.version));
        const suffix = params.toString() ? `?${params.toString()}` : '';
        return request<DatasetInspectionPayload>(
          `/api/datasets/${encodeURIComponent(namespace)}/${encodeURIComponent(name)}/inspect${suffix}`,
        );
      },
    },
    ontology: {
      catalog: () => request<OntologyCatalog>(`/api/ontology/catalog`),
      validate: (payload: OntologyValidateRequest) => request<OntologyValidationResult>(
        `/api/ontology/validate`,
        {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
        },
      ),
    },
    insights: {
      reviews: {
        list: (filters: InsightReviewListFilters = {}) => {
          const params = new URLSearchParams();
          if (filters.status) params.set('status', filters.status);
          if (filters.assigneeUserId) params.set('assigneeUserId', filters.assigneeUserId);
          if (filters.limit !== undefined) params.set('limit', String(filters.limit));
          const suffix = params.toString() ? `?${params.toString()}` : '';
          return request<InsightReviewQueryResult>(`/api/insights/reviews${suffix}`);
        },
        create: (payload: InsightReviewCreateRequest, options: { idempotencyKey: string }) =>
          request<InsightReviewPayload>(`/api/insights/reviews`, {
            method: "POST",
            headers: { "Content-Type": "application/json", "Idempotency-Key": requireIdempotencyKey(options?.idempotencyKey, "insights.reviews.create") },
            body: JSON.stringify(payload),
          }),
        get: (reviewId: string) =>
          request<InsightReviewPayload>(`/api/insights/reviews/${encodeURIComponent(reviewId)}`),
        assign: (
          reviewId: string,
          payload: InsightReviewAssignRequest,
          options: { idempotencyKey: string },
        ) =>
          request<InsightReviewPayload>(
            `/api/insights/reviews/${encodeURIComponent(reviewId)}/assign`,
            {
              method: "POST",
              headers: { "Content-Type": "application/json", "Idempotency-Key": requireIdempotencyKey(options?.idempotencyKey, "insights.reviews.assign") },
              body: JSON.stringify(payload),
            },
          ),
        decide: (
          reviewId: string,
          payload: InsightReviewDecisionRequest,
          options: { idempotencyKey: string },
        ) =>
          request<InsightReviewPayload>(
            `/api/insights/reviews/${encodeURIComponent(reviewId)}/decision`,
            {
              method: "POST",
              headers: { "Content-Type": "application/json", "Idempotency-Key": requireIdempotencyKey(options?.idempotencyKey, "insights.reviews.decide") },
              body: JSON.stringify(payload),
            },
          ),
      },
    },
    objects: {
      generic: {
        get: (objectType: string, id: string, options?: { explain?: boolean }) => {
          const suffix = options?.explain ? '?explain=true' : '';
          return request<GenericObject>(
            `/api/objects/${encodeURIComponent(objectType)}/${encodeURIComponent(id)}${suffix}`,
          );
        },
        query: (objectType: string, payload: ObjectQueryRequest = {}) =>
          request<ObjectQueryResult<GenericObject>>(`/api/objects/${encodeURIComponent(objectType)}/query`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          }),
        links: (objectType: string, id: string, linkType: string) =>
          request<ObjectLinkPayload[]>(
            `/api/objects/${encodeURIComponent(objectType)}/${encodeURIComponent(id)}` +
              `/links/${encodeURIComponent(linkType)}`,
          ),
      },
      Order: {
        get: (id: string, options?: { explain?: boolean }) => {
          const suffix = options?.explain ? '?explain=true' : '';
          return request<Order>(`/api/objects/Order/${encodeURIComponent(id)}${suffix}`);
        },
        query: (payload: ObjectQueryRequest = {}) =>
          request<ObjectQueryResult<Order>>(`/api/objects/Order/query`, {
            method: "POST",
            headers: { 'Content-Type': 'application/json', 'X-Foundry-Lite-Object': "Order" },
            body: JSON.stringify(payload),
          }),
      },
      Customer: {
        get: (id: string, options?: { explain?: boolean }) => {
          const suffix = options?.explain ? '?explain=true' : '';
          return request<Customer>(`/api/objects/Customer/${encodeURIComponent(id)}${suffix}`);
        },
        query: (payload: ObjectQueryRequest = {}) =>
          request<ObjectQueryResult<Customer>>(`/api/objects/Customer/query`, {
            method: "POST",
            headers: { 'Content-Type': 'application/json', 'X-Foundry-Lite-Object': "Customer" },
            body: JSON.stringify(payload),
          }),
      },
    },
    actions: {
      ApproveOrder: {
        apply: (payload: ApproveOrderApplyRequest) =>
          request<ActionApplyResponse>(`/api/actions/ApproveOrder/apply`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "Idempotency-Key": requireIdempotencyKey(
                payload.idempotencyKey,
                "ApproveOrder",
              ),
            },
            body: JSON.stringify({
              target: { objectType: "Order", objectId: payload.objectId },
              expectedObjectVersion: payload.expectedObjectVersion,
              params: payload.params,
            }),
          }),
      },
    },
    objectSets: {
      list: (filters: { objectType?: string } = {}) => {
        const suffix = filters.objectType ? `?objectType=${encodeURIComponent(filters.objectType)}` : '';
        return request<ObjectSetQueryResult>(`/api/object-sets${suffix}`);
      },
      create: (payload: ObjectSetCreateRequest) => request<ObjectSetPayload>(`/api/object-sets`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      }),
      get: (id: string) => request<ObjectSetPayload>(`/api/object-sets/${encodeURIComponent(id)}`),
    },
    materializations: {
      run: (apiName: string) => request<MaterializationRunResult>(
        `/api/materializations/${encodeURIComponent(apiName)}/run`,
        { method: "POST" },
      ),
    },
    operations: {
      runs: {
        list: (filters: RuntimeRunQueryFilters = {}) => {
          const params = new URLSearchParams();
          if (filters.runType) params.set('runType', String(filters.runType));
          if (filters.status) params.set('status', filters.status);
          if (filters.since) params.set('since', filters.since);
          if (filters.until) params.set('until', filters.until);
          if (filters.limit !== undefined) params.set('limit', String(filters.limit));
          if (filters.cursor) params.set('cursor', filters.cursor);
          const suffix = params.toString() ? `?${params.toString()}` : '';
          return request<RuntimeRunQueryResult>(`/api/operations/runs${suffix}`);
        },
        detail: (runType: string, runId: string) => request<RuntimeRunDetail>(
          `/api/operations/runs/${encodeURIComponent(runType)}/${encodeURIComponent(runId)}`,
        ),
      },
      backupRestore: {
        preflight: (payload: BackupRestorePreflightRequest = {}) =>
          request<BackupRestorePreflightReport>(`/api/operations/backup-restore/preflight`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          }),
        startRestoreMode: (payload: BackupRestoreModeStartRequest = {}) =>
          request<BackupRestoreModeReport>(`/api/operations/backup-restore/restore-mode/start`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          }),
        restoreModeStatus: (restoreId: string) =>
          request<BackupRestoreModeReport>(
            `/api/operations/backup-restore/restore-mode/${encodeURIComponent(restoreId)}`,
          ),
        approveResume: (restoreId: string, payload: BackupRestoreResumeApprovalRequest = {}) =>
          request<BackupRestoreModeReport>(
            `/api/operations/backup-restore/restore-mode/${encodeURIComponent(restoreId)}/approve-resume`,
            {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify(payload),
            },
          ),
      },
      deadLetterRecords: {
        list: (filters: { status?: DeadLetterRecordStatus } = {}) => {
          const suffix = filters.status ? `?status=${encodeURIComponent(filters.status)}` : '';
          return request<DeadLetterRecord[]>(`/api/operations/dead-letter-records${suffix}`);
        },
        get: (id: string) =>
          request<DeadLetterRecord>(`/api/operations/dead-letter-records/${encodeURIComponent(id)}`),
        retry: (id: string, options: { idempotencyKey: string }) =>
          request<DeadLetterRecordRetryResult>(
            `/api/operations/dead-letter-records/${encodeURIComponent(id)}/retry`,
            {
              method: "POST",
              headers: { "Idempotency-Key": requireIdempotencyKey(options?.idempotencyKey, "operations.deadLetterRecords.retry") },
            },
          ),
        bulkRetry: (ids: string[], options: { idempotencyKey: string }) =>
          request<DeadLetterRecordBulkRetryResult>(`/api/operations/dead-letter-records/bulk-retry`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "Idempotency-Key": requireIdempotencyKey(options?.idempotencyKey, "operations.deadLetterRecords.bulkRetry"),
            },
            body: JSON.stringify({ ids }),
          }),
        discard: (id: string) =>
          request<DeadLetterRecordDiscardResult>(
            `/api/operations/dead-letter-records/${encodeURIComponent(id)}/discard`,
            { method: "POST" },
          ),
      },
      deadLetterEvents: {
        retry: (id: string) => request<RuntimeRetryResult>(
          `/api/operations/dead-letter-events/${encodeURIComponent(id)}/retry`,
          { method: "POST" },
        ),
      },
      icebergMaintenance: {
        planReadOnly: (datasetRef: string, options: IcebergMaintenancePlanOptions = {}) => {
          const params = new URLSearchParams();
          params.set('datasetRef', datasetRef);
          if (options.branch) params.set('branch', options.branch);
          if (options.smallFileThresholdBytes !== undefined) {
            params.set('smallFileThresholdBytes', String(options.smallFileThresholdBytes));
          }
          if (options.fileCountThreshold !== undefined) {
            params.set('fileCountThreshold', String(options.fileCountThreshold));
          }
          if (options.readAmplificationThreshold !== undefined) {
            params.set('readAmplificationThreshold', String(options.readAmplificationThreshold));
          }
          if (options.retentionMinSnapshots !== undefined) {
            params.set('retentionMinSnapshots', String(options.retentionMinSnapshots));
          }
          return request<IcebergMaintenancePlan>(`/api/operations/maintenance/iceberg?${params.toString()}`);
        },
        plan: (datasetRef: string, options: IcebergMaintenancePlanOptions = {}) => {
          const params = new URLSearchParams();
          if (options.branch) params.set('branch', options.branch);
          if (options.smallFileThresholdBytes !== undefined) {
            params.set('smallFileThresholdBytes', String(options.smallFileThresholdBytes));
          }
          if (options.fileCountThreshold !== undefined) {
            params.set('fileCountThreshold', String(options.fileCountThreshold));
          }
          if (options.readAmplificationThreshold !== undefined) {
            params.set('readAmplificationThreshold', String(options.readAmplificationThreshold));
          }
          if (options.retentionMinSnapshots !== undefined) {
            params.set('retentionMinSnapshots', String(options.retentionMinSnapshots));
          }
          const suffix = params.toString() ? `?${params.toString()}` : '';
          return request<IcebergMaintenancePlan>(
            `/api/operations/maintenance/iceberg/${encodeURIComponent(datasetRef)}/plan${suffix}`,
            { method: "POST" },
          );
        },
      },
      index: {
        replayObjectType: (objectType: string) => request<ObjectIndexRebuildResult>(
          `/api/operations/index/${encodeURIComponent(objectType)}/replay`,
          { method: "POST" },
        ),
        replayFailedRun: (runId: string) => request<ObjectIndexRebuildResult>(
          `/api/operations/runs/index/${encodeURIComponent(runId)}/replay`,
          { method: "POST" },
        ),
      },
      lineage: {
        get: (resourceId: string) => {
          const params = new URLSearchParams();
          params.set('resourceId', resourceId);
          return request<LineageEdge[]>(`/api/operations/lineage?${params.toString()}`);
        },
      },
      observability: {
        detect: (payload: ObservabilityDetectRequest) =>
          request<ObservabilityReport>(`/api/operations/observability/detect`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          }),
      },
      reconciliation: {
        resolve: (writebackId: string, payload: ActionWritebackReconciliationRequest) =>
          request<ActionWritebackReconciliationResult>(
            `/api/operations/reconciliation/${encodeURIComponent(writebackId)}/resolve`,
            {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify(payload),
            },
          ),
      },
      transforms: {
        retry: (runId: string) => request<TransformRetryResult>(
          `/api/operations/runs/transform/${encodeURIComponent(runId)}/retry`,
          { method: "POST" },
        ),
      },
      workflows: {
        startConnectorSync: (payload: ConnectorSyncWorkflowStartRequest, options: { idempotencyKey: string }) =>
          request<ProductWorkflowRun>(`/api/operations/workflows/connector-sync/start`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "Idempotency-Key": requireIdempotencyKey(options?.idempotencyKey, "operations.workflows.startConnectorSync"),
            },
            body: JSON.stringify(payload),
          }),
        get: (workflowRunId: string) =>
          request<ProductWorkflowRun>(`/api/operations/workflows/${encodeURIComponent(workflowRunId)}`),
      },
    },
  };
}

