from __future__ import annotations

from pathlib import Path


def test_operations_ui_record_dlq_retry_shows_result() -> None:
    html = Path("apps/web/index.html").read_text(encoding="utf-8")

    expected_fragments = [
        'id="recordDlqStatus"',
        'id="recordDlqId"',
        'id="loadRecordDlqBtn"',
        'id="recordDlqDetailBtn"',
        'id="replayRecordDlqBtn"',
        'id="bulkReplayRecordDlqBtn"',
        'id="discardRecordDlqBtn"',
        'id="recordDlqResult"',
        'id="aipBuilderAgentVersion"',
        'id="aipBuilderReleaseChannel"',
        'id="aipBuilderModelAlias"',
        'id="aipBuilderPromptVersion"',
        'id="aipBuilderValidateBtn"',
        'id="aipBuilderRunBtn"',
        'id="aipAgentRunBtn"',
        'id="aipBuilderResult"',
        'id="aipBuilderGraph"',
        'id="aipAgentResult"',
        'id="aipAgentAnswer"',
        'id="aipAgentCitations"',
        "renderAipAgentCitations",
        "citationCard",
        "sourcePreviewBlock",
        "citation-preview-grid",
        "Source preview",
        "agentCitationOutputSchema",
        'id="metricAipBuilderStatus"',
        'id="metricAipBuilderNodes"',
        'id="metricAipBuilderIssues"',
        'id="metricAipAgentStatus"',
        'id="metricAipAgentContext"',
        'id="metricAipAgentTokens"',
        '<option value="ai">AI</option>',
        'id="requestIdText"',
        'id="errorKindText"',
        'id="retryableText"',
        "createRequestId",
        "normalizeFoundryLiteError",
        "isRetryableFoundryLiteError",
        "requestIdFactory",
        "onResponse: updateRequestTelemetry",
        'tenantId: "tenant-demo"',
        'userId: "web-demo-operator"',
        'roles: ["ops_manager", "data_engineer", "finance"]',
        "sdkClient().system.health",
        "client.datasets.versions",
        "client.datasets.preview",
        "sdkClient().ontology.validate",
        "sdkClient().objects.generic.get",
        "sdkClient().objects.generic.query",
        "sdkClient().objects.generic.links",
        "sdkClient().objectSets.create",
        "sdkClient().objectSets.list",
        "sdkClient().materializations.run",
        "sdkClient().operations.runs.list",
        "sdkClient().operations.runs.detail",
        "sdkClient().operations.index.replayObjectType",
        "sdkClient().operations.index.replayFailedRun",
        "sdkClient().operations.transforms.retry",
        "sdkClient().operations.deadLetterEvents.retry",
        'id="metricLateData"',
        'id="metricImpactRuns"',
        'id="metricImpactRoots"',
        "sdkClient().operations.deadLetterRecords.list",
        "sdkClient().operations.deadLetterRecords.get",
        "sdkClient().operations.deadLetterRecords.retry",
        "sdkClient().operations.deadLetterRecords.bulkRetry",
        "sdkClient().operations.deadLetterRecords.discard",
        "sdkClient().aip.builder.validate",
        "sdkClient().aip.builder.run",
        "sdkClient().aip.agent.run",
        "lastRecordReplay",
        "lastRecordDiscard",
        "impactPreview",
        "lateDataBadge",
        "downstreamImpact",
    ]

    for fragment in expected_fragments:
        assert fragment in html

    forbidden_fragments = [
        "sdkClient().request(",
        "async function request(",
        'request("/api',
        "request('/api",
        "request(`/api",
    ]
    for fragment in forbidden_fragments:
        assert fragment not in html
